feat(orders): change order status on label print
myparcelnl/woocommerce pull request #1016
Opened 2023-09-19 13:35 UTC by Mark-Ernst

2023-09-19 14:39 UTC, wthijmen approved these changes

2023-09-20 07:23 UTC, EdieLemoine requested changes

2023-09-20 07:23 UTC, EdieLemoine commented on tests/Unit/Service/WcStatusServiceTest.php
> +    createWcOrder(['id' => 33]);
deze functie is deprecated (zoals je editor zou moeten aangeven), gebruik de factory direct

2023-09-20 07:23 UTC, EdieLemoine commented on tests/Mock/MockWcOrder.php
> +    public function get_status(): string
deze functie is niet nodig, als je per se defaults wil wijzigen kun je dit doen:

```
protected $attributes = [
  'status' => '',
];
```

maar check eerst maar of dat echt nodig is

2023-09-20 09:00 UTC, EdieLemoine approved these changes

2023-09-20 09:05 UTC, EdieLemoine requested changes

2023-09-20 09:05 UTC, EdieLemoine commented on src/Pdk/Plugin/Service/WcStatusService.php
> +     * @return array|string[]
```suggestion
     * @return array<string, string>
```

2023-09-20 11:36 UTC, EdieLemoine approved these changes

2023-09-20 11:37 UTC, merged