fix(migration): finish migration even when api key is faulty
myparcelnl/woocommerce pull request #1023
Opened 2023-09-29 13:24 UTC by joerivanveen

2023-09-29 13:36 UTC, EdieLemoine requested changes

2023-09-29 13:36 UTC, EdieLemoine commented on tests/Unit/Migration/Pdk/Migration5_0_0Test.php
> +            AccountSettings::ID => [
niet zo doen, gebruik factories (dit is oud, achterhaald en werkt straks niet meer)

2023-09-29 15:08 UTC, EdieLemoine commented on tests/Unit/Migration/Pdk/Migration5_0_0Test.php
> +        ->make();
dit doet nu niks, als je het gemaakte object wil returnen gebruik je `make()`, en als je het op wil slaan doe je `store()`

2023-09-29 19:51 UTC, EdieLemoine approved these changes

2023-10-02 09:00 UTC, Mark-Ernst approved these changes

2023-10-02 09:03 UTC, merged