fix(export): fix multiple automatic exports
myparcelnl/woocommerce pull request #1034
Opened 2023-10-12 11:59 UTC by Mark-Ernst

2023-10-12 12:22 UTC, EdieLemoine requested changes

2023-10-12 13:49 UTC, EdieLemoine approved these changes

2023-10-12 13:58 UTC, RichardPerdaan commented
Ik ben het niet helemaal eens met deze fix. klanten moeten zelf kunnen kiezen wanneer de klant de order doorzet naar de api. Ik denk dat er eerder een check gemaakt moet worden of deze zending al geëxporteerd is?

2023-10-16 08:11 UTC, joerivanveen approved these changes

2023-10-16 08:30 UTC, merged