fix(php-scoper): exclude symfony
myparcelnl/woocommerce pull request #1043
Opened 2023-10-23 14:56 UTC by Mark-Ernst

INT-7

2023-10-24 09:45 UTC, wthijmen approved these changes

2023-10-24 14:40 UTC, EdieLemoine requested changes
Waarom? Woo/wordpress heeft geen Symfony

2023-10-24 14:48 UTC, Mark-Ernst commented
> Waarom? Woo/wordpress heeft geen Symfony

Nee maar onze PDK wel en dat pakketje met die namespaces fokt bestanden in Symfony op (bv. symfony>polyfill-intl-normalizer>Normalizer.php)

2023-10-25 10:13 UTC, EdieLemoine commented
@Mark-Ernst dat is juist waarom we symfony moeten scopen, je kunt beter een andere oplossing zoeken want dit mist het doel van het scopen op zich. Nu zouden we juist weer conflicten krijgen met plugins die ook stukjes symfony gebruiken

2023-10-27 07:45 UTC, closed without merging