fix(cronservice): make callable usable
myparcelnl/woocommerce pull request #1052
Opened 2023-11-14 10:54 UTC by joerivanveen

2023-11-16 15:29 UTC, Mark-Ernst approved these changes

2023-11-17 09:17 UTC, EdieLemoine requested changes

2023-11-17 09:17 UTC, EdieLemoine commented on src/Pdk/WcPdkBootstrapper.php
> +            'myParcelActions' => value("{$name}_all_actions"),
de titels hiervan kunnen beter

2023-11-17 09:17 UTC, EdieLemoine commented on src/Service/WpCronService.php
> +            $actions[sprintf('%s%s', Pdk::get('myParcelHook'), $hook)] = $callback;
variabelen en dergelijke mag je gewoon concatenaten, de "niet concatenaten" regel geldt alleen wanneer je ook echt strings in de mix hebt

2023-11-17 09:17 UTC, EdieLemoine commented on src/Service/WpCronService.php
> +            $actions[sprintf('%s%s', Pdk::get('myParcelHook'), $hook)] = [
idem

2023-11-17 09:17 UTC, EdieLemoine commented on src/Service/WpCronService.php
> +                get_class($callback[0]),
die array indexes zijn niet zo veilig (of duidelijk), kan je hier iets eleganters op bedenken

2023-11-17 09:17 UTC, EdieLemoine commented on tests/Unit/Service/WpCronServiceTest.php
> +                Pdk::get('myParcelHook'),
hier ook weer ff normaal concatenaten, en zet het meteen in een variabele want je doet het hieronder weer

2023-11-17 09:17 UTC, EdieLemoine commented on tests/Unit/Service/WpCronServiceTest.php
> +it('can call a callable', function () {
heel goed dat er tests geschreven zijn!!!! 🥳

2023-11-17 09:17 UTC, EdieLemoine commented on woocommerce-myparcel.php
> +        array_map(static function ($callback, $hook) use ($actions) {
in dit stuk mist coverage, en het is een beetje slordig zo hier. gaarne in een aparte functie zetten 🙏🏼

2023-11-21 08:29 UTC, EdieLemoine approved these changes

2023-11-21 08:57 UTC, merged