Feat: add audits
myparcelnl/woocommerce pull request #1053
Opened 2023-11-16 08:40 UTC by Mark-Ernst

2023-11-17 09:40 UTC, EdieLemoine requested changes

2023-11-17 09:40 UTC, EdieLemoine commented on src/Migration/Migration5_0_0.php
> +        $this->createAuditTable();
dit mag gewoon in een migratie zoals hierboven

2023-11-17 09:40 UTC, EdieLemoine commented on src/Hooks/AutomaticOrderExportHooks.php
> +        if ($newStatus === $automaticExportStatus) {
unhappy flow eerst

2023-11-17 09:40 UTC, EdieLemoine commented on src/Hooks/CheckoutScriptHooks.php
> +            ) ?? 'woocommerce_after_checkout_billing_form'
deze string mag hier niet, en hier is al wat moois voor, zie `filterDefaults` in de bootstrapper

2023-11-23 14:08 UTC, wthijmen approved these changes

2023-11-24 08:22 UTC, EdieLemoine requested changes

2023-11-24 08:22 UTC, EdieLemoine commented on phpstan-baseline.php
> +	'message' => '#^Method MyParcelNL\\\\Pdk\\\\Base\\\\Contract\\\\WeightServiceInterface\\:\\:convertToGrams\\(\\) invoked with 1 parameter, 2 required\\.$#',
je hebt een nieuwe error toegevoegd, dat ken niet

2023-11-28 09:29 UTC, EdieLemoine approved these changes

2023-11-28 14:30 UTC, merged