fix(cronservice): return array instead of callable on validateArrayCallback
myparcelnl/woocommerce pull request #1056
Opened 2023-11-22 09:50 UTC by wthijmen

2023-11-22 10:55 UTC, Mark-Ernst approved these changes

2023-11-23 08:16 UTC, EdieLemoine requested changes
titel is niet goed, wat lost dit op?

2023-11-23 08:16 UTC, EdieLemoine commented on tests/__snapshots__/SettingsMigrationTest__it_migrates_pre_v5.0.0_settings_with_data_set_empty__1.json
> -    "id": "account",
formatting is niet goed, je editor settings kloppen niet. installeer je husky hooks

2023-11-23 08:47 UTC, EdieLemoine approved these changes

2023-11-23 08:48 UTC, merged