feat(checkout): add blocks compatibility
myparcelnl/woocommerce pull request #1065
Opened 2024-01-16 12:31 UTC by Mark-Ernst

2024-01-24 11:13 UTC, Mark-Ernst commented
@EdieLemoine schrik niet van de webpack config. Deze moet nog geconverteerd worden naar een vite config. Daar heb ik wellicht een beetje hulp bij nodig

2024-01-24 11:28 UTC, EdieLemoine requested changes

2024-01-24 11:28 UTC, EdieLemoine commented on DeliveryOptionsBlocksIntegration.php
> +        $this->register_myparcel_delivery_options_block_frontend_scripts();
deze methods hoeven niet public, niet zo lang, en niet in snake case

2024-01-24 11:28 UTC, EdieLemoine commented on DeliveryOptionsBlocksIntegration.php
> +        $customCss      = Settings::get(
dit kan vgm op 1 regel

2024-01-24 11:28 UTC, EdieLemoine commented on DeliveryOptionsBlocksIntegration.php
> +        $contextService = Pdk::get(ContextServiceInterface::class);
phpdocs missen

2024-01-24 11:28 UTC, EdieLemoine commented on DeliveryOptionsBlocksIntegration.php
> +use Automattic\WooCommerce\Blocks\Integrations\IntegrationInterface;
dit bestand mag hier niet

2024-01-24 11:28 UTC, EdieLemoine commented on DeliveryOptionsBlocksIntegration.php
> +
strict types mist

2024-01-24 11:28 UTC, EdieLemoine commented on DeliveryOptionsBlocksIntegration.php
> + * Class for integrating with WooCommerce Blocks
onnodige doc

2024-02-09 15:12 UTC, EdieLemoine requested changes
er zijn nog steeds heel veel uncovered backend regels

2024-02-09 15:12 UTC, EdieLemoine commented on package.json
> +    "start": "wp-scripts start",
dit mag weg

2024-02-09 15:12 UTC, EdieLemoine commented on package.json
> +    "sass-loader": "^13.3.3",
dit mag weg

2024-02-09 15:12 UTC, EdieLemoine commented on src/Integration/DeliveryOptionsBlocksIntegration.php
> +    public function get_editor_script_handles(): array
zorg ff dat je uitzonderingen voor die codacy regels hierin zet

2024-02-09 15:12 UTC, EdieLemoine commented on src/Pdk/Hooks/PdkCheckoutPlaceOrderHooks.php
> +        global $HTTP_RAW_POST_DATA;
hier ook uitzondering voor de linter(s)

2024-02-23 17:02 UTC, EdieLemoine approved these changes

2024-02-29 08:20 UTC, merged