feat: HPOS incompatibility warning
myparcelnl/woocommerce pull request #1109
Opened 2024-06-04 12:30 UTC by GravendeelJochem

INT-498

2024-06-05 06:26 UTC, FlorianSDV approved these changes

2024-06-07 06:50 UTC, joerivanveen approved these changes

2024-06-07 06:50 UTC, joerivanveen commented on woocommerce-myparcel.php
> +Tested up to: 6.5.4
```suggestion
Tested up to: 6.5
```

2024-06-07 09:00 UTC, EdieLemoine requested changes
je titel is niet goed, check [dit bestand](https://github.com/myparcelnl/developer/blob/main/DEVELOPERS.md#commit-messages) voor instructies

2024-06-11 07:18 UTC, merged