fix(checkout): make it so delivery options is displayed in correct position
myparcelnl/woocommerce pull request #1188
Opened 2024-11-04 09:42 UTC by FlorianSDV

INT-708

2024-11-05 08:44 UTC, joerivanveen approved these changes

2024-11-05 08:44 UTC, joerivanveen commented on src/Contract/WooCommerceServiceInterface.php
> +use WC_Blocks_Utils;
Deze heb je hier toch niet nodig?

2024-11-05 08:44 UTC, joerivanveen commented on src/Pdk/WcPdkBootstrapper.php
> +use WC_Blocks_Utils;
Deze heb je hier toch ook niet nodig? Verwijdert jouw phpStorm de ongebruikte use dingen niet on save?

2024-11-05 10:26 UTC, FlorianSDV commented on src/Contract/WooCommerceServiceInterface.php
> +use WC_Blocks_Utils;
Ik heb het verwijdert

2024-11-05 10:30 UTC, FlorianSDV commented on src/Pdk/WcPdkBootstrapper.php
> +use WC_Blocks_Utils;
Dankjewel, het was inderdaad een instelling die uit stond. Ik heb de import verwijdert.

2024-11-05 10:37 UTC, GravendeelJochem approved these changes

2024-11-06 10:36 UTC, EdieLemoine requested changes

2024-11-06 10:36 UTC, EdieLemoine commented on src/Contract/WooCommerceServiceInterface.php
> +     * @see https://stackoverflow.com/a/77950175
dit hoeft hier niet

2024-11-06 10:36 UTC, EdieLemoine commented on src/Contract/WooCommerceServiceInterface.php
> +
formatting klopt niet

2024-11-06 10:36 UTC, EdieLemoine commented on tests/Unit/Hooks/CheckoutScriptHooksTest.php
> +            ->withDeliveryOptionsPosition('woocommerce_after_checkout_billing_form')
Dit komt nergens terug en is dus geen test of die waarde wel correct terugkomt ofzo

2024-11-08 14:31 UTC, EdieLemoine commented on src/Hooks/CheckoutScriptHooks.php
> +        return $position ?: 'woocommerce_after_checkout_billing_form';
dit is waar filterDefaults voor zijn, moet je niet direct in je code schrijven

2024-11-08 14:32 UTC, EdieLemoine commented on tests/mock_wc_functions.php
> +/** @param  string $page Page slug.
formatting klopt niet

2024-11-08 16:06 UTC, EdieLemoine approved these changes

2024-11-14 08:57 UTC, merged