fix: failing tests ups new options
myparcelnl/woocommerce pull request #1220
Opened 2024-12-20 14:13 UTC by GravendeelJochem

2024-12-20 14:57 UTC, FreekVR commented
Kun je commit message nog corrigeren? Subject moet test zijn, want het is geen bugfix in de code, alleen tests zijn aangepast.

`test: update tests for new UPS options in PDK`

2024-12-20 15:00 UTC, FreekVR requested changes
zie eerdere comment

2024-12-23 09:23 UTC, joerivanveen approved these changes

2024-12-23 12:47 UTC, FreekVR approved these changes

2024-12-23 12:50 UTC, merged