Feat/country of origin select
myparcelnl/woocommerce pull request #391
Opened 2020-09-21 07:15 UTC by robindelaater

2020-09-21 07:26 UTC, EdieLemoine requested changes

2020-09-21 07:26 UTC, EdieLemoine commented on includes/admin/class-wcmp-admin.php
> +            if ($productOption['type'] === 'select' && empty($productOption['options'])) {
Kom op, dat kan veeeel korter :P 
```php
if ($productOption['type'] === 'select') {
    woocommerce_wp_select(
        [
            'id'          => $productOption['id'],
            'label'       => $productOption['label'],
            'options'     => $productOption['options'] ?? [
                    __("Disabled", "woocommerce-myparcel"),
                    __("Enabled", "woocommerce-myparcel"),
                ],
            'description' => $productOption['description'],
        ]
    );
}

2020-09-21 07:58 UTC, robindelaater commented on includes/admin/class-wcmp-admin.php
> +            if ($productOption['type'] === 'select' && empty($productOption['options'])) {
hihi

2020-09-21 07:59 UTC, robindelaater commented on includes/admin/class-wcmp-admin.php
> +            if ($productOption['type'] === 'select' && empty($productOption['options'])) {
done

2020-09-21 08:05 UTC, reindert-vetter submitted a review, later dismissed

2020-09-21 08:06 UTC, EdieLemoine submitted a review, later dismissed

2020-09-28 07:06 UTC, RichardPerdaan submitted a review, later dismissed

2020-10-01 07:06 UTC, RichardPerdaan submitted a review, later dismissed

2020-10-01 08:05 UTC, EdieLemoine requested changes

2020-10-01 08:05 UTC, EdieLemoine commented on includes/admin/settings/class-wcmp-settings-data.php
> +              "options"   => (new WC_Countries)->get_countries(),
```suggestion
              "options"   => (new WC_Countries())->get_countries(),
```
Heeft wat mij betreft (en in [PSR-12)](https://www.php-fig.org/psr/psr-12/#4-classes-properties-and-methods) de voorkeur

2020-10-01 08:09 UTC, EdieLemoine approved these changes

2020-10-01 08:13 UTC, RichardPerdaan approved these changes

2020-10-01 09:41 UTC, EdieLemoine approved these changes

2020-10-01 09:43 UTC, RichardPerdaan approved these changes

2020-10-01 09:44 UTC, merged