Restore missing {{myparcel_delivery_date}} placeholder
myparcelnl/woocommerce pull request #411
Opened 2020-10-08 12:44 UTC by Spreeuw

WooCommerce PDF Invoices & Packing Slips Premium Templates compatibility
This particular placeholder got left out in the 4.0 upgrade (while it was present in 3.x). I wasn't sure whether to place it in `includes/compatibility/class-wcpdf-compatibility.php` or ` includes/frontend/class-wcmp-frontend.php` but since the former appears to be used specifically for the track & trace placeholders I opted for the latter. Might be good to bundle them all together in the compatibility class after all?

2020-10-09 13:26 UTC, EdieLemoine requested changes

2020-10-09 13:26 UTC, EdieLemoine commented on includes/frontend/class-wcmp-frontend.php
> +     * @param $order
Could you write the param type(s) here?

2020-10-09 13:26 UTC, EdieLemoine commented on includes/frontend/class-wcmp-frontend.php
> +        if ( $deliveryDate = $deliveryOptions->getDate() ) {
Could you remove spaces inside `if ()` and move the assignment out of it?

2020-10-09 14:00 UTC, RichardPerdaan approved these changes

2020-10-10 09:39 UTC, Spreeuw commented
2 additional bugs were reported and I decided to include them in this pull request because they're closely related:

1. the {{myparcel_tracktrace}} placeholder no longer worked - this turned out to have been accidentally renamed from you end. I have restored this (for backwards compatibility) and added the new placeholder name as a synonym
2. the filters in `includes/compatibility/class-wcpdf-compatibility.php` were linked to the wrong class name (without the namespace), I have replaced this by `__CLASS__`.

2020-10-15 10:17 UTC, RichardPerdaan approved these changes

2020-10-20 09:48 UTC, EdieLemoine approved these changes

2020-10-21 13:13 UTC, wahidnory commented
This getting merged?

2020-11-12 20:54 UTC, phemels commented
@RichardPerdaan When will this be fixed? In version 4.1.2 it's still an issue :(

2020-11-23 08:57 UTC, RichardPerdaan commented
Because there were a lot of merge conflicts, when I changed it to master, I used the changes and generated a new PR (#474)

2020-11-23 08:57 UTC, closed without merging

2020-11-26 18:58 UTC, phemels commented
MyParcel 4.1.4 geinstalleerd.
Krijg nu deze error als ik een pakbon wil maken:

![image](https://user-images.githubusercontent.com/29940263/100384997-c8738500-3021-11eb-98cf-b5fba3bc8349.png)