Feature: Error handling on bulk export
myparcelnl/woocommerce pull request #500
Opened 2020-12-15 10:12 UTC by robindelaater

2020-12-15 15:51 UTC, RichardPerdaan approved these changes

2020-12-15 15:53 UTC, RichardPerdaan requested changes

2020-12-15 15:53 UTC, RichardPerdaan commented on includes/admin/class-wcmp-api.php
> +		        continue;
continue is niet helemaal uitgelijnd

2020-12-15 15:53 UTC, RichardPerdaan commented on includes/admin/class-wcmp-export.php
> +		        $this->updateOrderStatus($order);
De lijken ook niet goed uitgelijnd

2020-12-17 08:57 UTC, EdieLemoine approved these changes

2020-12-18 09:34 UTC, RichardPerdaan approved these changes

2020-12-29 09:26 UTC, RichardPerdaan requested changes

2020-12-29 09:26 UTC, RichardPerdaan commented on assets/js/wcmp-admin.js
> +          // }
De code die uitgezet is, mag weg

2020-12-29 09:26 UTC, RichardPerdaan commented on assets/js/wcmp-admin.js
> +  }
getCookie wordt nergens gebruikt?

2020-12-29 10:55 UTC, RichardPerdaan approved these changes

2020-12-29 11:29 UTC, merged