Delivery option in order confirmation
myparcelnl/woocommerce pull request #524
Opened 2021-01-12 10:57 UTC by RichardPerdaan

2021-01-12 11:52 UTC, robindelaater submitted a review, later dismissed

2021-01-12 12:17 UTC, EdieLemoine requested changes

2021-01-12 12:17 UTC, EdieLemoine commented on gulpfile.js
> +  gulp.watch(['**/*.php'], null, gulp.series('translations:pot'));
wat moooooi :D

2021-01-12 12:17 UTC, EdieLemoine commented on includes/admin/class-wcmypa-admin.php
> +		$emailConfirmation ? $this->printEmailConfirmation($confirmationData) : $this->printThankYouConfirmation($confirmationData);
ik weet niet hoe het kan maar je indenting gaat hier helemaal mis

2021-01-12 12:17 UTC, EdieLemoine commented on includes/admin/class-wcmypa-admin.php
> +	public function showShipmentConfirmation(WC_Order $order, bool $emailConfirmation): void
misschien toch nog `$emailConfirmation` hernoemen naar `$isEmail`

2021-01-12 12:17 UTC, EdieLemoine commented on includes/admin/class-wcmypa-admin.php
> +        $signatureTitle     = (new WCMP_Checkout)->getDeliveryOptionsTitle(WCMYPA_Settings::SETTING_SIGNATURE_TITLE);
Volgens mij doen we altijd parens `()` bij een constructor, en nu ben je dit ding 2x aan het aanmaken. Kun je `new WCMP_Checkout()` in een variabele stoppen? En misschien te out of scope, maar moet `getDeliveryOptionsTitle` niet gewoon static zijn?

2021-01-12 12:17 UTC, EdieLemoine commented on includes/admin/class-wcmypa-admin.php
> +
enter te veel

2021-01-12 12:17 UTC, EdieLemoine commented on includes/admin/class-wcmypa-admin.php
> +        if ($deliveryOptions->getDeliveryType() === AbstractConsignment::DELIVERY_TYPE_PICKUP_NAME) {
Yoda comparisons (dus constante eerst) 

Als je het hier niet mee eens bent hoor ik het graag maar het is een standaard die gebruikt wordt in de API :)

2021-01-12 12:17 UTC, EdieLemoine commented on includes/admin/class-wcmypa-admin.php
> +                __("Pickup location:", "woocommerce-myparcel") =>
meerdere soorten quotes door elkaar

2021-01-12 12:17 UTC, EdieLemoine commented on includes/admin/class-wcmypa-admin.php
> +                  $deliveryOptions->getPickupLocation()->getLocationName() . '<br>' .
Kan je dit converteren naar sprintf? Phpstorm heeft daar een actie voor. Ik denk dat het het iets nicer maakt.

2021-01-12 12:17 UTC, EdieLemoine commented on includes/admin/class-wcmypa-admin.php
> +              ($deliveryOptions->getShipmentOptions()->hasSignature() ? $signatureTitle . '<br>' : null) .
hier ook liever sprintf

2021-01-12 12:17 UTC, EdieLemoine commented on includes/admin/class-wcmypa-admin.php
> +                  $deliveryOptions->getPickupLocation()->getLocationName() . '<br>' .
misschien ook ff de pickup location in een variabele stoppen, scheelt een hoop leeswerk

2021-01-12 12:17 UTC, EdieLemoine commented on includes/admin/class-wcmypa-admin.php
> +    public function printThankYouConfirmation($selectedDeliveryOptions){
je mist types hier en in de docs, en er mist een spatie tussen `)` en `{`

2021-01-12 12:17 UTC, EdieLemoine commented on includes/admin/class-wcmypa-admin.php
> +    public function printEmailConfirmation($selectedDeliveryOptions){
je mist types hier en in de docs, en er mist een spatie tussen `)` en `{`

2021-01-12 12:17 UTC, EdieLemoine commented on includes/admin/class-wcmypa-admin.php
> +     * Print in the confirmation email a table with the chosen delivery options.
`Print a table with the chosen delivery options in the confirmation email.`

2021-01-12 12:17 UTC, EdieLemoine commented on includes/admin/class-wcmypa-admin.php
> +     * Print in on the confirmation page a table with the chosen delivery options.
`Print a table with the chosen delivery options on the confirmation page.`

2021-01-12 12:17 UTC, EdieLemoine commented on includes/admin/class-wcmypa-admin.php
> +      return null;
hier gaat de indenting ook fout, misschien even alles wat je aangepast hebt opnieuw formatten

2021-01-12 12:17 UTC, EdieLemoine commented on includes/admin/class-wcmypa-admin.php
> +          $htmlHeader .= $table . "</table>";
`$table` lijkt helemaal niet nodig, je kunt alles direct appenden op `$htmlHeader` toch?

2021-01-12 12:17 UTC, EdieLemoine commented on includes/frontend/class-wcmp-frontend.php
> +		$order_id = WCX_Order::get_id($order);
weer rare indenting, check ook even je phpstorm settings 🤔

2021-01-12 12:17 UTC, EdieLemoine commented on includes/frontend/class-wcmp-frontend.php
> +		if ($consignments = WCMP_Frontend::getTrackTraceLinks($order_id)) {
assignment in een if is best wel vies, kun je er een variabele van maken en hem eruit trekken?

2021-01-12 12:17 UTC, EdieLemoine commented on includes/frontend/class-wcmp-frontend.php
> +	    WCMYPA()->admin->showShipmentConfirmation($order, true);
indenting

2021-01-13 10:18 UTC, EdieLemoine submitted a review, later dismissed

2021-01-13 12:24 UTC, EdieLemoine approved these changes

2021-01-15 09:05 UTC, robindelaater submitted a review, later dismissed

2021-01-15 13:23 UTC, robindelaater approved these changes

2021-01-18 09:01 UTC, EdieLemoine approved these changes

2021-01-18 09:48 UTC, robindelaater approved these changes

2021-01-18 10:01 UTC, merged