fix: delivery options returning 'null'
myparcelnl/woocommerce pull request #528
Opened 2021-01-13 16:14 UTC by EdieLemoine

2021-01-13 16:15 UTC, RichardPerdaan approved these changes

2021-01-15 09:07 UTC, robindelaater approved these changes

2021-01-15 09:56 UTC, mknijnenberg approved these changes

2021-01-18 07:56 UTC, jonathanheijmans approved these changes

2021-01-18 07:56 UTC, jonathanheijmans commented on src/js/wcmp-frontend.js
> +      MyParcelFrontend.hiddenDataInput.value = value;
Je had hier ook een ternary operator kunnen gebruiken. Is wel prima zo.

```
MyParcelFrontend.hiddenDataInput.value = event.detail === null ? '' : JSON.stringify(event.detail);
```

2021-01-18 07:59 UTC, jonathanheijmans requested changes

2021-01-18 07:59 UTC, jonathanheijmans commented on src/js/wcmp-frontend.js
> +      MyParcelFrontend.hiddenDataInput.value = value;
Moet je ook niet checken op undefined?

2021-01-18 08:01 UTC, jonathanheijmans approved these changes

2021-01-18 08:24 UTC, merged