Fix undefined error visible
myparcelnl/woocommerce pull request #530
Opened 2021-01-14 12:32 UTC by robindelaater

2021-01-15 14:55 UTC, RichardPerdaan requested changes

2021-01-15 14:55 UTC, RichardPerdaan commented on languages/woocommerce-myparcel-fr_BE.po
> +
Waarom is hier een enter geplaatst?

2021-01-15 14:55 UTC, RichardPerdaan commented on languages/woocommerce-myparcel-nl_BE.po
> +
Waarom is hier een enter geplaatst?

2021-01-15 14:55 UTC, RichardPerdaan commented on languages/woocommerce-myparcel-nl_BE.po
> -msgstr "Hoe update je jouw PHP versie"
waarom is deze vertaling verwijderd?

2021-01-15 15:02 UTC, RichardPerdaan submitted a review, later dismissed

2021-01-18 09:04 UTC, EdieLemoine requested changes

2021-01-18 09:04 UTC, EdieLemoine commented on composer.json
> +        "myparcelnl/sdk": "^5.2"
Waarom verander je dit?

2021-01-18 09:50 UTC, robindelaater commented on composer.json
> +        "myparcelnl/sdk": "^5.2"
Heb t teruggezet naar hoe t was

2021-01-18 10:09 UTC, EdieLemoine approved these changes

2021-01-18 10:09 UTC, RichardPerdaan approved these changes

2021-01-18 11:05 UTC, RichardPerdaan approved these changes

2021-01-18 11:12 UTC, merged