Fix age check not working
myparcelnl/woocommerce pull request #546
Opened 2021-01-19 16:40 UTC by robindelaater

2021-01-19 16:49 UTC, RichardPerdaan requested changes

2021-01-19 16:49 UTC, RichardPerdaan commented on includes/admin/OrderSettings.php
>      }
Moet het product niet leidend zijn en zodra die niet gezet is dat hij dan naar de settings kijkt?

2021-01-20 16:11 UTC, EdieLemoine approved these changes

2021-01-20 16:11 UTC, RichardPerdaan approved these changes

2021-01-20 16:11 UTC, merged