fix json flag error and clean up some delivery options code
myparcelnl/woocommerce pull request #569
Opened 2021-02-19 10:57 UTC by EdieLemoine

2021-02-19 13:22 UTC, RichardPerdaan approved these changes

2021-02-22 08:50 UTC, reindert-vetter requested changes

2021-02-22 08:50 UTC, reindert-vetter commented on includes/adapter/shipment-options-from-order-adapter.php
> +    private const DEFAULT_INSURANCE = 0;
draait dit op 7.1?

2021-02-22 09:02 UTC, reindert-vetter approved these changes

2021-02-22 09:28 UTC, merged