My 27283 delivery options price format
myparcelnl/woocommerce pull request #574
Opened 2021-02-25 13:08 UTC by RichardPerdaan

2021-02-25 15:02 UTC, adem-demir approved these changes

2021-02-26 08:06 UTC, adem-demir submitted a review, later dismissed

2021-03-01 15:24 UTC, EdieLemoine requested changes

2021-03-02 07:35 UTC, RichardPerdaan commented on includes/frontend/class-wcmp-checkout.php
> +                "showPriceSurcharge" => $priceFormat === WCMP_Settings_Data::DISPLAY_SURCHARGE_PRICE,
done

2021-03-02 07:36 UTC, RichardPerdaan commented on includes/admin/settings/class-wcmp-settings-data.php
> +                "label"     => __("checkout_options_price_format", "woocommerce-myparcel"),
done

2021-03-02 07:36 UTC, RichardPerdaan commented on includes/admin/settings/class-wcmp-settings-data.php
> +                "default"   => self::DISPLAY_TOTAL_PRICE,
done

2021-03-02 08:18 UTC, EdieLemoine approved these changes

2021-03-02 08:41 UTC, adem-demir approved these changes

2021-03-05 12:49 UTC, merged