fix ship_to_different_address check in validation
myparcelnl/woocommerce pull request #579
Opened 2021-03-02 14:35 UTC by Spreeuw

closes #578

2021-03-05 10:32 UTC, EdieLemoine requested changes

2021-03-05 10:32 UTC, EdieLemoine commented on includes/class-wcmp-postcode-fields.php
> +            && ! empty( $address['ship_to_different_address'] )
Minor code style detail:
```suggestion
            && ! empty($address['ship_to_different_address'])
```

2021-03-09 08:30 UTC, EdieLemoine approved these changes

2021-03-11 08:46 UTC, RichardPerdaan approved these changes

2021-03-25 08:31 UTC, merged