feat: option change order status after export or after printing
myparcelnl/woocommerce pull request #602
Opened 2021-03-23 14:03 UTC by RichardPerdaan

2021-03-25 13:05 UTC, EdieLemoine requested changes

2021-03-25 13:05 UTC, EdieLemoine commented on includes/admin/class-wcmp-api.php
> +        if ($statusAutomation && $changeStatusAfter === $changeStatus) {
ik snap niet wat hier gebeurt (en waarom), kun je duidelijkere namen voor de variabelen bedenken?

2021-03-26 09:01 UTC, RichardPerdaan commented on includes/admin/class-wcmp-api.php
> +        if ($statusAutomation && $changeStatusAfter === $changeStatus) {
done

2021-03-26 09:04 UTC, EdieLemoine approved these changes

2021-03-26 09:41 UTC, reindert-vetter approved these changes

2021-03-26 09:59 UTC, merged