Fix: insurance is not properly saved.
myparcelnl/woocommerce pull request #608
Opened 2021-03-25 15:45 UTC by RichardPerdaan

There is also a check if the minimum insurance or higher has been chosen on the basis of the carrier.

2021-03-25 15:48 UTC, reindert-vetter approved these changes

2021-03-25 16:12 UTC, EdieLemoine requested changes

2021-03-25 16:12 UTC, EdieLemoine commented on includes/admin/OrderSettings.php
> +        if ($insuranceFromDeliveryOptions || $insuranceFromDeliveryOptions < next($amountPossibilities)) {
next? why? kan dit niet op een moderne (=leesbare) manier?

2021-03-26 08:51 UTC, RichardPerdaan commented on includes/admin/OrderSettings.php
> +        if ($insuranceFromDeliveryOptions || $insuranceFromDeliveryOptions < next($amountPossibilities)) {
Done

2021-03-26 09:04 UTC, EdieLemoine approved these changes

2021-03-26 09:40 UTC, reindert-vetter approved these changes

2021-03-26 11:21 UTC, merged