My 27832 deliveryoptions map or list default
myparcelnl/woocommerce pull request #622
Opened 2021-04-06 12:21 UTC by joerivanveen

Added a list (select) with 'map' and 'list' in the settings checkout settings tab below 'show prices as', default 'map'
added method getPickupLocationsDefaultView() in class-wcmp-checkout to yield this value
translation strings added in google sheet: settings_pickup_locations_default_view, settings_pickup_locations_map, settings_pickup_locations_list

2021-04-06 12:45 UTC, EdieLemoine requested changes

2021-04-06 12:45 UTC, EdieLemoine commented on includes/admin/settings/class-wcmp-settings-data.php
> +                    self::PICKUP_LOCATIONS_VIEW_MAP     => __(
Die `=>` lijkt niet goed uitgelijnd

2021-04-06 12:45 UTC, EdieLemoine commented on includes/admin/settings/class-wcmp-settings-data.php
> +                        "settings_pickup_locations_map",
De namen van de opties graag prefixen met de hele setting naam, dus `settings_pickup_locations_default_view_map` en `settings_pickup_locations_default_view_list`. Maakt niet uit dat het dan idioot lange namen worden :P

2021-04-06 12:45 UTC, EdieLemoine commented on includes/frontend/class-wcmp-checkout.php
> +        $pickupLocationsDefaultView = self::getPickupLocationsDefaultView();
Dit is zo simpel, de variabele is niet nodig wat mij betreft

2021-04-06 12:45 UTC, EdieLemoine commented on languages/woocommerce-myparcel-fr_FR.po
> +msgstr "Lester"
...Lester? 😂

2021-04-06 12:45 UTC, EdieLemoine commented on languages/woocommerce-myparcel-fr_FR.po
> +"exemple proposer une r��duction pour cette fonction ou décompter des frais "
even opnieuw importeren, dit gaat niet goed

2021-04-06 12:46 UTC, EdieLemoine commented on languages/woocommerce-myparcel-fr_FR.po
> +msgstr "Lester"
Ik heb dit gefixt, stond fout in de sheet

2021-04-06 15:02 UTC, RichardPerdaan requested changes

2021-04-06 15:02 UTC, RichardPerdaan commented on includes/frontend/class-wcmp-checkout.php
Waarom zijn hier spaties bij gekomen?

2021-04-08 08:47 UTC, EdieLemoine approved these changes

2021-04-08 11:54 UTC, RichardPerdaan approved these changes

2021-04-08 15:07 UTC, adem-demir approved these changes

2021-04-15 07:33 UTC, merged