fix: check if package type is set in _myparcel_shipment_options meta
myparcelnl/woocommerce pull request #651
Opened 2021-05-20 12:28 UTC by RichardPerdaan

Issue: https://wordpress.org/support/topic/meta-field-returns-1-ipv-array/

2021-05-20 12:51 UTC, joerivanveen submitted a review, later dismissed

2021-05-20 12:56 UTC, EdieLemoine requested changes

2021-05-20 12:56 UTC, EdieLemoine commented on includes/admin/class-wcmp-export.php
> +
Je zou ook dit kunnen doen:

```php
return (string) WCMP_Data::getPackageTypeId($shipmentOptions['package_type'] ?? AbstractConsignment::DEFAULT_PACKAGE_TYPE_NAME);
```
En om het nog beter te maken kan je regel 943 naar boven verplaatsen:
```php
$packageType = AbstractConsignment::DEFAULT_PACKAGE_TYPE_NAME;
```
Dan kan je dit doen: 
```php
return (string) WCMP_Data::getPackageTypeId($shipmentOptions['package_type'] ?? $packageType);
```

2021-05-20 12:56 UTC, EdieLemoine commented on includes/admin/class-wcmp-export.php
> +
En als je dat niks vindt worden zou ik tenminste dit aanpassen zodat je nog maar 1x cast naar string:

```php
  if (isset($shipmentOptions['package_type'])) {
      $packageType = WCMP_Data::getPackageTypeId($shipmentOptions['package_type']);
  }

  return (string) ($packageType ?? AbstractConsignment::DEFAULT_PACKAGE_TYPE);
```

2021-05-23 18:50 UTC, adem-demir approved these changes

2021-05-31 14:55 UTC, merged