Add country of origin option to variable product
myparcelnl/woocommerce pull request #663
Opened 2021-06-21 11:20 UTC by adem-demir

2021-06-22 08:28 UTC, EdieLemoine requested changes

2021-06-22 08:28 UTC, EdieLemoine commented on includes/admin/class-wcmp-export-consignments.php
> +        return $this->getPriorityOrigin($defaultCountryOfOrigin, $productCountryOfOrigin, $variationCountryOfOrigin);
Dit, en de hele functie `getPriorityOrigin` kan worden vervangen door dit:

```php
// ...
$fallbackCountryOfOrigin = WC()->countries->get_base_country() ?? AbstractConsignment::CC_NL

return $variationCountryOfOrigin ?? $productCountryOfOrigin ?? $defaultCountryOfOrigin ?? $fallbackCountryOfOrigin;
```

2021-06-22 08:28 UTC, EdieLemoine commented on includes/admin/class-wcmypa-admin.php
> +    public function variationCountryOfOriginField($loop, $variationData, $variation)
types? als het hier niet kan moet het alsnog in de phpdoc

2021-06-22 08:28 UTC, EdieLemoine commented on includes/admin/class-wcmypa-admin.php
> +        add_action('woocommerce_product_after_variable_attributes', [$this, 'variationCountryOfOriginField'], 10, 3);
ik zou die functie `renderVariationCountryOfOriginField` noemen

2021-06-22 08:28 UTC, EdieLemoine commented on includes/admin/class-wcmypa-admin.php
> +                'label'         => __('country_of_origin_variable', 'woocommerce-myparcel'),
ik vind dit geen goede naam voor de vertaling key, misschien iets wat begint met `product_variable_` om hem soort van te namespacen daarop

2021-06-22 08:28 UTC, EdieLemoine commented on includes/admin/class-wcmypa-admin.php
> +    public function saveVariationCountryOfOriginField($variationId, $loop)
types

2021-06-22 08:28 UTC, EdieLemoine commented on includes/admin/class-wcmypa-admin.php
> +    public function loadVariationCountryOfOriginField($variation)
types

2021-06-22 15:11 UTC, EdieLemoine requested changes

2021-06-22 15:11 UTC, EdieLemoine commented on includes/admin/class-wcmypa-admin.php
>       * @return mixed
Hier moet array staan

2021-06-22 15:11 UTC, EdieLemoine commented on includes/admin/class-wcmypa-admin.php
> +    public function saveVariationCountryOfOriginField(int $variationId, int $loop)
Dit returnt `void`

2021-06-22 15:11 UTC, EdieLemoine commented on includes/admin/class-wcmypa-admin.php
> +    public function renderVariationCountryOfOriginField(int $loop, array $variationData, object $variation)
return void

2021-06-22 15:44 UTC, EdieLemoine approved these changes

2021-06-22 17:00 UTC, RichardPerdaan approved these changes

2021-06-24 07:07 UTC, joerivanveen submitted a review, later dismissed

2021-07-06 15:23 UTC, merged