Add empty weight for digital stamp shipments
myparcelnl/woocommerce pull request #665
Opened 2021-06-22 09:56 UTC by adem-demir

2021-06-22 10:21 UTC, joerivanveen requested changes

2021-06-22 10:21 UTC, joerivanveen commented on includes/admin/settings/class-wcmp-settings-data.php
> +            [
Graag enkele aanhalingstekens gebruiken bij nieuwe dingen

2021-06-22 10:21 UTC, joerivanveen commented on includes/admin/settings/class-wcmypa-settings.php
> +    public const SETTING_EMPTY_DIGITAL_STAMP_WEIGHT     = "empty_digital_stamp_weight";
Ook graag gewoon enkele aanhalingstekens bij nieuwe constanten

2021-06-22 11:18 UTC, EdieLemoine requested changes

2021-06-22 11:18 UTC, EdieLemoine commented on includes/admin/settings/class-wcmp-settings-data.php
> +                    __("empty_digital_stamp_weight", "woocommerce-myparcel"),
de translation keys moeten geprefixed worden met `setting_`

2021-06-23 11:39 UTC, EdieLemoine requested changes

2021-06-23 11:39 UTC, EdieLemoine commented on includes/admin/OrderSettings.php
> +        $emptyWeight  = (float) WCMYPA()->setting_collection->getByName(WCMYPA_Settings::SETTING_EMPTY_DIGITAL_STAMP_WEIGHT);
uitlijnen

2021-06-23 11:39 UTC, EdieLemoine commented on includes/admin/settings/class-wcmp-settings-data.php
> +            [
Ik zie nog steeds dubbele quotes

2021-06-23 12:13 UTC, adem-demir commented on includes/admin/settings/class-wcmp-settings-data.php
> +            [
ik dacht het alleen om de vertalingen dingen was

2021-06-23 15:17 UTC, RichardPerdaan approved these changes

2021-06-24 07:02 UTC, joerivanveen submitted a review, later dismissed

2021-07-02 17:20 UTC, merged