fix: ignore virtual products when creating consignment
myparcelnl/woocommerce pull request #678
Opened 2021-07-13 12:25 UTC by joerivanveen

2021-07-15 08:52 UTC, RichardPerdaan approved these changes

2021-07-15 09:38 UTC, RichardPerdaan requested changes
Als er 2 producten in de order zit en het 1e product is een virtual dan zal het het 2e product niet genoteerd worden

2021-07-15 11:25 UTC, RichardPerdaan submitted a review, later dismissed

2021-07-19 09:15 UTC, EdieLemoine commented on includes/admin/class-wcmp-export-consignments.php
> +            if ($product->is_virtual()) {
Getver wat een grote loop 😢  klopt die return hierboven wel of had dat ook eigenlijk een continue moeten zijn? Weet dat het niet direct met je codes te maken heeft maar als je er toch bent... En straks komt het ineens uit de test omdat er grondiger naar gekeken gaat worden!

2021-07-19 11:02 UTC, EdieLemoine requested changes

2021-07-19 11:02 UTC, EdieLemoine commented on includes/admin/class-wcmp-export-consignments.php
> +        return round(($total + $tax) * 100);
Hier kan nooit een float uit komen, je hoeft niet te `round`en

2021-07-19 11:02 UTC, EdieLemoine commented on includes/admin/class-wcmp-export-consignments.php
> +     * @throws \ErrorException|\JsonException
Waar komt die jsonexception vandaan? die is php 7.3+ 😨

2021-07-19 11:48 UTC, EdieLemoine approved these changes

2021-07-19 12:09 UTC, RichardPerdaan approved these changes

2021-07-21 12:00 UTC, merged