fix: check shipment type before empty DPZ is calculated
myparcelnl/woocommerce pull request #682
Opened 2021-07-15 12:42 UTC by RichardPerdaan

2021-07-15 13:00 UTC, joerivanveen submitted a review, later dismissed

2021-07-19 13:53 UTC, EdieLemoine requested changes

2021-07-19 13:53 UTC, EdieLemoine commented on includes/admin/OrderSettings.php
> +        if (AbstractConsignment::PACKAGE_TYPE_DIGITAL_STAMP_NAME === $this->getPackageType()){
spatie tussen ){

2021-07-19 13:53 UTC, EdieLemoine commented on includes/admin/OrderSettings.php
> +            $emptyWeight  = (float) WCMYPA()->setting_collection->getByName(
te veel spaties voor =

2021-07-19 13:55 UTC, RichardPerdaan commented on includes/admin/OrderSettings.php
> +        if (AbstractConsignment::PACKAGE_TYPE_DIGITAL_STAMP_NAME === $this->getPackageType()){
```suggestion
        if (AbstractConsignment::PACKAGE_TYPE_DIGITAL_STAMP_NAME === $this->getPackageType()) {
```

2021-07-19 13:55 UTC, RichardPerdaan commented on includes/admin/OrderSettings.php
> +            $emptyWeight  = (float) WCMYPA()->setting_collection->getByName(
```suggestion
            $emptyWeight = (float) WCMYPA()->setting_collection->getByName(
```

2021-07-19 14:02 UTC, EdieLemoine approved these changes

2021-07-21 11:58 UTC, merged