fix: return extra options without extra linebreaks
myparcelnl/woocommerce pull request #693
Opened 2021-09-02 12:29 UTC by joerivanveen

2021-09-06 10:55 UTC, EdieLemoine requested changes

2021-09-06 10:55 UTC, EdieLemoine commented on includes/admin/class-wcmypa-admin.php
> +                __("delivery_type", "woocommerce-myparcel")   => WCMP_Data::getDeliveryTypesHuman(
Hij wordt hier wel een beetje vies afgebroken

2021-09-06 10:55 UTC, EdieLemoine commented on includes/admin/class-wcmypa-admin.php
> +            $confirmationData[__('Date:', 'woocommerce')] = wc_format_datetime(new WC_DateTime($deliveryOptions->getDate()));;
dubbele `;`

2021-09-06 12:03 UTC, EdieLemoine approved these changes

2021-09-14 10:45 UTC, RichardPerdaan approved these changes

2021-09-15 13:24 UTC, merged