My 30158 label in the box
myparcelnl/woocommerce pull request #717
Opened 2021-11-03 09:22 UTC by RichardPerdaan

2021-11-03 13:30 UTC, EdieLemoine requested changes

2021-11-03 13:30 UTC, EdieLemoine commented on includes/admin/class-wcmp-export.php
> +        if (WCMP_Settings_Data::NOT_ACTIVE === $returnOptions || WCMP_Settings_Data::NOT_ACTIVE === null) {
Een const vergelijken met `null`?

2021-11-04 08:48 UTC, joerivanveen commented on includes/admin/class-wcmp-export.php
> +        if (WCMP_Settings_Data::NOT_ACTIVE === $returnOptions || ! $returnOptions) {
Geen showstopper maar het komt mij logischer over deze andersom te doen.

2021-11-04 08:49 UTC, EdieLemoine approved these changes

2021-11-04 08:59 UTC, joerivanveen approved these changes

2021-11-05 14:00 UTC, merged