fix: allow old shipping methods
myparcelnl/woocommerce pull request #720
Opened 2021-11-11 19:21 UTC by joerivanveen

2021-11-12 08:01 UTC, RichardPerdaan approved these changes

2021-11-16 08:20 UTC, EdieLemoine requested changes

2021-11-16 08:20 UTC, EdieLemoine commented on includes/admin/class-wcmp-export.php
> +    public function getOrderShippingClass(WC_Order $order, string $shippingMethodId = '')
geen `?string`?

2021-11-16 12:28 UTC, RichardPerdaan submitted a review, later dismissed

2021-11-16 12:53 UTC, EdieLemoine submitted a review, later dismissed

2021-11-16 12:57 UTC, EdieLemoine submitted a review, later dismissed

2021-11-16 13:03 UTC, RichardPerdaan approved these changes

2021-11-18 08:40 UTC, EdieLemoine approved these changes

2021-11-18 13:22 UTC, RichardPerdaan approved these changes

2021-11-23 13:50 UTC, merged