My 30513 fix set insurance data condition skip
myparcelnl/woocommerce pull request #734
Opened 2021-11-26 08:40 UTC by markernst97

2021-11-26 08:42 UTC, EdieLemoine requested changes

2021-11-26 08:42 UTC, EdieLemoine commented on includes/admin/OrderSettings.php
> +        if ($insuranceFromDeliveryOptions && $insuranceFromDeliveryOptions >= array_shift($amountPossibilities)) {
Ik hou niet zo van dit soort functies, maar ik heb dan liever `reset()` in plaats van deze. `array_shift()` past de array aan, en als je dit zo leest weet je niet direct dat daar dan toevallig verder niks mee gedaan wordt. `reset()` is iets minder verwarrend.

2021-11-26 09:37 UTC, RichardPerdaan approved these changes

2021-11-29 09:32 UTC, EdieLemoine approved these changes

2021-12-08 08:02 UTC, merged