feat: disable insurance for shipments to Belgium
myparcelnl/woocommerce pull request #744
Opened 2021-12-20 07:37 UTC by markernst97

2021-12-21 08:41 UTC, joerivanveen commented on includes/admin/MessagesRepository.php
> +        if (in_array($currentPage->id, $message['onPages'], true)) {
Witregel?

2021-12-21 08:48 UTC, joerivanveen approved these changes

2021-12-21 08:48 UTC, joerivanveen commented on includes/admin/OrderSettings.php
> +            $isInsured = $isDefaultInsuredForBE;
Uitlijning

2021-12-21 08:48 UTC, joerivanveen commented on includes/admin/OrderSettings.php
>      public const DEFAULT_COLLO_AMOUNT = 1;
Uitlijning

2021-12-21 08:59 UTC, EdieLemoine requested changes

2021-12-21 08:59 UTC, EdieLemoine commented on includes/admin/MessagesRepository.php
> +    public function addMessage(string $message, string $level, ?string $messageId, array $onPages = []): void
je kunt `$messageId` hier ook een default waarde van null geven

2021-12-21 08:59 UTC, EdieLemoine commented on includes/admin/MessagesRepository.php
> +                echo sprintf(
`echo sprintf` -> `printf`

De static analysis tool wordt helemaal gek hier, misschien kan je kijken naar hoe je dit moet escapen in de WordPress Developer Handbooks die vermeld wordt

2021-12-21 08:59 UTC, EdieLemoine commented on includes/admin/MessagesRepository.php
> +    private function shouldMessageBeShown(array $message): bool
phpdoc

2021-12-21 08:59 UTC, EdieLemoine commented on includes/admin/MessagesRepository.php
> +        return false;
een hele boel return statements is heel slecht leesbaar, kan je kijken of dit simpeler kan?

2021-12-21 08:59 UTC, EdieLemoine commented on includes/admin/MessagesRepository.php
> +            if (! in_array($message['messageId'], $messageArray, true)) {
Graag de happy path op het eind, zodat hij niet indented is en je (hier toevallig) geen negated condition gebruikt, dus zoiets:

```js
if (true) {
  continue;
}

codes...
```

ipv 
```js
if (false) {
  codes...
}
```

_ProTip: Ga in phpstorm op `if (` staan, druk op option+enter en kies "Invert 'if' statement"_

2021-12-21 08:59 UTC, EdieLemoine commented on includes/admin/OrderSettings.php
> +    public const DEFAULT_BELGIAN_INSURANCE = 500;
uitlijnen

2021-12-21 08:59 UTC, EdieLemoine commented on includes/admin/OrderSettings.php
> +            $isInsured = $isDefaultInsuredForBE;
uitlijnen

2021-12-21 08:59 UTC, EdieLemoine commented on includes/admin/OrderSettings.php
> +            $isInsured = $isDefaultInsuredForBE;
Dit is eigenlijk een hele losse tak van de bovenstaande if statements toch? Dan kan je deze ook aan het begin hangen als de eerste `if`. Nu lijkt het in eerste oogopslag alsof er in deze if nog wat kan gebeuren met een eerder gewijzigde waarde van  `$isInsured` en `$insuranceAmount`

2021-12-21 08:59 UTC, EdieLemoine commented on includes/admin/OrderSettingsRows.php
> +        if($isBelgium) {
formatting

2021-12-21 08:59 UTC, EdieLemoine commented on includes/admin/OrderSettings.php
> +            $isInsured = $isDefaultInsuredForBE;
Vgm kan je `! $insuranceFromDeliveryOptions && $isBelgium && $isDefaultInsured` doen en dan ook in de volgende 2 takken de checks op `$insuranceFromDeliveryOptions` weglaten

2021-12-21 08:59 UTC, EdieLemoine commented on includes/admin/settings/CarrierSettings.php
> +                    'label'     => __('shipment_options_insured_for_be', 'woocommerce-myparcel'),
Ik wacht met smart op de dag dat dit ineens ook voor andere landen moet... 🥲

2021-12-21 08:59 UTC, EdieLemoine commented on includes/class-wcmp-assets.php
> +            ["ajax_url"               => admin_url("admin-ajax.php"),
single quotes

2021-12-21 08:59 UTC, EdieLemoine commented on includes/class-wcmp-assets.php
> +             "nonce"                  => wp_create_nonce(WCMYPA::NONCE_ACTION),]
formatting is lelijk, volgens mij mist er een indent

2021-12-21 08:59 UTC, EdieLemoine commented on languages/woocommerce-myparcel-en_GB.po
> +msgstr ""
de translations kan je beter reverten, anders krijg je een merge conflict

2021-12-21 08:59 UTC, EdieLemoine commented on woocommerce-myparcel.php
> +            // Show temporary message concerning insurances for shipments to Belgium.
misschien een TODO erbij met wanneer hij weggehaald moet worden, dan is ie wat makkelijker te vinden

2021-12-21 08:59 UTC, EdieLemoine commented on src/js/wcmp-admin-all-pages.js
> +      $.post(wcmp_params.ajax_url, data, () => {
die lege callback mag weg

2021-12-21 08:59 UTC, EdieLemoine commented on src/js/wcmp-admin-all-pages.js
> +  $(document).ready(() => {
Deze hoeft vgm niet, jquery() doet al zoiets

2021-12-21 08:59 UTC, EdieLemoine commented on src/js/wcmp-admin-all-pages.js
> +    $(document).on('click', '.myparcel-dismiss-notice .notice-dismiss', () => {
Graag deze callback refactoren naar een named function

2021-12-21 08:59 UTC, EdieLemoine commented on src/js/wcmp-admin-all-pages.js
> +jQuery(($) => {
Dit bestand heeft nu nog maar 1 doel, dus misschien ook de naam wat minder obscuur houden voor nu. `wcmp-admin-notices.js` misschien?

2021-12-21 08:59 UTC, EdieLemoine commented on includes/class-wcmp-assets.php
> +        self::enqueueJs('wcmp-admin-all-pages', 'wcmp-admin-all-pages.js', ['jquery']);
waarom moet je hier jquery vermelden maar hierboven ook?

2021-12-23 12:37 UTC, EdieLemoine approved these changes

2021-12-23 14:19 UTC, joerivanveen submitted a review, later dismissed

2021-12-23 15:43 UTC, RichardPerdaan submitted a review, later dismissed

2021-12-28 12:22 UTC, joerivanveen submitted a review, later dismissed

2021-12-28 12:29 UTC, RichardPerdaan submitted a review, later dismissed

2021-12-28 13:25 UTC, joerivanveen approved these changes

2021-12-28 13:45 UTC, RichardPerdaan approved these changes

2021-12-29 10:43 UTC, merged