feat: persist notices over requests
myparcelnl/woocommerce pull request #753
Opened 2021-12-31 12:01 UTC by joerivanveen

2022-01-18 11:29 UTC, markernst97 submitted a review, later dismissed

2022-01-18 13:52 UTC, EdieLemoine requested changes

2022-01-18 13:52 UTC, EdieLemoine commented on includes/admin/MessagesRepository.php
> +        if ($this->messages) {
Zelfs hier liever eerst de unhappy path 🧙🏼

2022-01-18 13:52 UTC, EdieLemoine commented on includes/admin/MessagesRepository.php
> +        return 0 < count(array_filter($this->messages, static function ($entry) use ($message) {
Je kunt nog een type hint toevoegen aan `$entry`

2022-01-18 13:52 UTC, EdieLemoine commented on woocommerce-myparcel.php
> +        private function checkPreRequisites(): bool
Prerequisites is één woord :)

2022-01-18 13:52 UTC, EdieLemoine commented on woocommerce-myparcel.php
> +            $how_to_update = __('How to update your PHP version', 'woocommerce-myparcel');
camelcase!

2022-01-18 13:52 UTC, EdieLemoine commented on woocommerce-myparcel.php
> +            $how_to_update = __('How to update your PHP version', 'woocommerce-myparcel');
Is het niet eens tijd om al die creepy externe-factoren-functies naar een trait of andere class te trekken? :/ Kan je ook de hele error bijvoorbeeld abstraheren naar `<wcmp> requires <thing> <version constraints>`

2022-01-18 13:52 UTC, EdieLemoine commented on woocommerce-myparcel.php
> +            $how_to_update = __('How to update your PHP version', 'woocommerce-myparcel');
^ hoeft niet hoor, maar heel graag (als je je geroepen voelt en tijd hebt) 😛

2022-01-19 12:57 UTC, RichardPerdaan approved these changes

2022-01-19 14:29 UTC, markernst97 approved these changes

2022-01-21 09:51 UTC, merged