fix: use price of single item instead of total price
myparcelnl/woocommerce pull request #755
Opened 2022-01-04 16:10 UTC by markernst97

2022-01-06 08:34 UTC, EdieLemoine approved these changes

2022-01-06 08:35 UTC, RichardPerdaan approved these changes

2022-01-06 08:39 UTC, joerivanveen requested changes

2022-01-06 08:39 UTC, joerivanveen commented on includes/adapter/OrderLineFromWooCommerce.php
> +        $wcProduct  = $wcOrderItem->get_product();
Dit is zo'n plek waar product null kan zijn wanneer het deleted is, graag rekening mee houden.

2022-01-06 08:50 UTC, joerivanveen commented on includes/adapter/OrderLineFromWooCommerce.php
>          $vat   = (int) ($wcItemData['subtotal_tax'] * 100.0);
Let op dat in de orderregel nu de prijs per product staat (zoals bepaald door pps), maar de BELASTING nog steeds voor de hele regel!

2022-01-06 08:51 UTC, joerivanveen commented on includes/adapter/OrderLineFromWooCommerce.php
>          $vat   = (int) ($wcItemData['subtotal_tax'] * 100.0);
Let op dat in de orderregel nu de prijs per product staat (zoals bepaald door pps), maar de BELASTING nog steeds voor de hele regel!

2022-01-06 08:54 UTC, joerivanveen commented on includes/adapter/OrderLineFromWooCommerce.php
> +        $wcProduct  = $wcOrderItem->get_product();
Na het kijken naar mijn eigen pr, zou ik denken dit mogelijk anders op te lossen, zodat er altijd een product doorgegeven wordt en een prijs, omdat dat wel essentieel is in dit geval, door zelf de orderline prijs (en evt. vat) terug te rekenen op basis van quantity, zodat de api het weer kan vermenigvuldigen. Dus ik zou doen:
`$price = ($wcItemData[' subtotal'] * 100 / $wcOrderItem->get_quantity());`
Ofzoiets maar dan mooi. En net zoiets voor de vat. Dan ben je voor deze essentiele regel niet afhankelijk van wel of niet bestaan van het product.

2022-01-06 13:02 UTC, joerivanveen approved these changes

2022-01-07 08:45 UTC, RichardPerdaan approved these changes

2022-01-07 13:17 UTC, merged