fix(pps): separate street from number when exporting order
myparcelnl/woocommerce pull request #756
Opened 2022-01-05 14:22 UTC by markernst97

2022-01-06 08:33 UTC, EdieLemoine requested changes

2022-01-06 08:33 UTC, EdieLemoine commented on includes/adapter/RecipientFromWCOrder.php
> +        return $emailConnected
Hoeft dit niet meer voor pickup?

2022-01-06 08:33 UTC, EdieLemoine commented on includes/admin/OrderSettings.php
>       * @TODO MY-28781 refactor OrderSettings-> get and set Shipping and Billing Recipients
Is deze todo nog relevant?

2022-01-06 08:36 UTC, joerivanveen commented on includes/admin/OrderSettings.php
>       * @TODO MY-28781 refactor OrderSettings-> get and set Shipping and Billing Recipients
Volgens mij niet idd

2022-01-06 08:36 UTC, RichardPerdaan commented on includes/adapter/RecipientFromWCOrder.php
> +        return $emailConnected
volgens mij moet er voor pickup altijd een email worden meegegeven

2022-01-06 08:38 UTC, joerivanveen commented on includes/adapter/RecipientFromWCOrder.php
> +        if (isset($streetParts['number_suffix']) && $addressLine2IsNumberSuffix) {
Dit ziet er raar uit voor mij nu: wanneer number_suffix bestaat in streetParts moet het overschreven worden? En als het niet bestaat, wordt het dus niet overschreven ook niet als addresLine2IsNumberSuffix? Als het klopt heb ik niets gezegd natuurlijk.

2022-01-06 08:38 UTC, joerivanveen submitted a review, later dismissed

2022-01-07 08:49 UTC, RichardPerdaan approved these changes

2022-01-07 09:01 UTC, joerivanveen approved these changes

2022-01-10 10:00 UTC, EdieLemoine approved these changes

2022-01-10 10:03 UTC, merged