feat: add same day shipment option
myparcelnl/woocommerce pull request #764
Opened 2022-01-11 14:34 UTC by joerivanveen

2022-01-14 15:33 UTC, markernst97 submitted a review, later dismissed

2022-01-18 08:48 UTC, RichardPerdaan requested changes
Moet er niet gecontroleerd worden of de sameday wel mogelijk is voor een specifieke carrier?
Ik verwacht als je nu een zending aanmaakt met PostNL dat je dan een error krijgt.

2022-01-18 08:54 UTC, joerivanveen commented
In de SDK wordt gecheckt of een carrier dit aanbiedt. Wanneer wel dan verschijnt de optie (in modal en settings tabblad), wanneer niet, verschijnt die niet. Het wordt ook gecheckt in de setter, wanneer een carrier de optie niet ondersteund, wordt die genegeerd in de setter, dus blijft ie false. Alleen wanneer die ondersteund wordt kan die op true gezet worden.

2022-01-18 08:56 UTC, RichardPerdaan approved these changes

2022-01-26 09:24 UTC, RichardPerdaan approved these changes

2022-01-26 09:58 UTC, EdieLemoine requested changes

2022-01-26 09:58 UTC, EdieLemoine commented on includes/adapter/OrderLineFromWooCommerce.php
> +        $quantity   = $wcOrderItem->get_quantity();
uitlijning

2022-01-26 09:58 UTC, EdieLemoine commented on includes/adapter/shipment-options-from-order-adapter.php
> +        return null;
Waarom niet zoiets? Ik vind dit wat fijner omdat je dan in de return statement direct de logica/volgorde erachter ziet ipv dat je de functie moet "lezen" 😷 
```php
$valueFromOptions = $options['same_day_delivery'] ?? null;
$valueFromAdapter = $shipmentOptionsAdapter ? $shipmentOptionsAdapter->isSameDayDelivery() : null;

return $valueFromOptions ?? $valueFromAdapter;
```

2022-01-26 09:58 UTC, EdieLemoine commented on includes/admin/class-wcmp-export.php
> +            $wcOrder                = WCX::get_order($orderId);
uitlijning

2022-01-26 09:58 UTC, EdieLemoine commented on includes/admin/class-wcmp-export.php
> +            $deliveryOptions->getShipmentOptions()->setSignature($orderSettings->hasSignature());
Als je shipment options ff in een variabele zet kan het volgende blok statements wat korter

2022-01-26 12:07 UTC, RichardPerdaan approved these changes

2022-01-26 12:47 UTC, EdieLemoine requested changes

2022-01-26 12:47 UTC, EdieLemoine commented on includes/adapter/shipment-options-from-order-adapter.php
> +        $valueFromOptions = (bool) ($options['age_check'] ?? null);
die (bool) hier gaat niet werken, nu is $valueFromOptions altijd true/false en kan hij nooit terugvallen naar $valueFromAdapter, je kunt wel dit doen:

```
return (bool) ($valueFromOptions ?? $valueFromAdapter);
```

2022-01-26 14:16 UTC, RichardPerdaan approved these changes

2022-01-26 15:34 UTC, RichardPerdaan approved these changes

2022-01-26 15:38 UTC, markernst97 approved these changes

2022-01-26 16:33 UTC, merged