Refactor/instabox
myparcelnl/woocommerce pull request #767
Opened 2022-01-24 13:12 UTC by RichardPerdaan

2022-01-24 13:19 UTC, markernst97 submitted a review, later dismissed

2022-01-24 13:21 UTC, EdieLemoine submitted a review, later dismissed

2022-01-26 10:58 UTC, markernst97 submitted a review, later dismissed

2022-01-26 11:07 UTC, EdieLemoine requested changes

2022-01-26 11:07 UTC, EdieLemoine commented on includes/admin/class-wcmypa-admin.php
> +            if ($meta['carrier'] === self::OLD_RED_JE_PAKKETJE_NAME) {
yoda!

2022-01-26 11:07 UTC, EdieLemoine commented on includes/admin/class-wcmypa-admin.php
> +            if ($meta['carrier'] === self::OLD_RED_JE_PAKKETJE_NAME) {
En kun je dit in een losse functie zetten? Het is al lelijk genoeg dat het zo moet, maar verstop het dan tenminste in een `normalize...` functie oid

2022-01-26 11:58 UTC, markernst97 approved these changes

2022-01-26 13:44 UTC, merged