fix(pps): add weight when exporting orders
myparcelnl/woocommerce pull request #769
Opened 2022-01-25 11:49 UTC by markernst97

2022-01-25 12:11 UTC, EdieLemoine requested changes

2022-01-25 12:11 UTC, EdieLemoine commented on includes/admin/class-wcmp-export-consignments.php
> +    public static function getTotalWeight($orderSettings): int
Heeft $orderSettings ook nog een type?

2022-01-25 12:11 UTC, EdieLemoine commented on includes/admin/class-wcmp-export-consignments.php
> +    public static function getTotalWeight($orderSettings): int
En als dat een class is, kan deze functie dan niet beter daarheen verhuizen?

2022-01-27 09:28 UTC, joerivanveen submitted a review, later dismissed

2022-01-27 09:28 UTC, joerivanveen commented on includes/admin/OrderSettings.php
> +    public function getTotalWeight(): int
Dit is wel een uitgelezen kans om de misleidende naam 'getTotalWeight' te refactoren. Deze geeft namelijk het gewicht PER PAKKETJE terug, NIET van de hele order. Ik stel me voor dat je een getTotalWeight hebt, en een getColloWeight ofzo die daar gebruik van maakt en de (juiste) verpakking erbij telt.

2022-01-31 13:45 UTC, joerivanveen approved these changes

2022-02-01 08:42 UTC, RichardPerdaan submitted a review, later dismissed

2022-02-02 08:28 UTC, merged