fix: insurance amount showing when shipment type is not package
myparcelnl/woocommerce pull request #771
Opened 2022-01-27 13:56 UTC by markernst97

2022-01-27 14:07 UTC, joerivanveen approved these changes

2022-01-27 14:38 UTC, EdieLemoine requested changes

2022-01-27 14:38 UTC, EdieLemoine commented on includes/admin/OrderSettingsRows.php
> +                    self::CONDITION_PACKAGE_TYPE_PACKAGE
trailing comma 🥲

2022-01-28 12:49 UTC, joerivanveen approved these changes

2022-01-28 12:57 UTC, EdieLemoine approved these changes

2022-01-28 13:14 UTC, merged