fix: display ordergrid even when an address is faulty
myparcelnl/woocommerce pull request #772
Opened 2022-01-27 15:07 UTC by joerivanveen

2022-01-27 15:15 UTC, EdieLemoine requested changes

2022-01-27 15:15 UTC, EdieLemoine commented on includes/admin/OrderSettings.php
> +                $this->order, $localCountryCode, RecipientFromWCOrder::SHIPPING
onder elkaar is wat leesbaarder

2022-01-27 15:15 UTC, EdieLemoine commented on includes/admin/OrderSettings.php
> +            \WCMP_Log::add(
dit en \exception mag je importeren

2022-01-27 15:15 UTC, EdieLemoine commented on includes/admin/OrderSettings.php
> +                    'Failed to create shipping recipient from order %s',
als je %d gebruikt ipv %s hoef je niet te casten naar string :)

2022-01-27 15:15 UTC, EdieLemoine commented on includes/admin/OrderSettings.php
> +                $this->order, $localCountryCode, RecipientFromWCOrder::BILLING
Kunnen deze 2 brokken niet gewoon in 1 functie? Zodat je alleen dit hoeft aan te roepen:

```php
$this->shippingRecipient = $this->createRecipient(RecipientFromWCOrder::SHIPPING);
// ...
$this->billingRecipient = $this->createRecipient(RecipientFromWCOrder::BILLING);
```

edit: zie nu dat het al zo was, dus je hoeft het niet meteen helemaal te refactoren, maar als je dat wel ziet zitten... graag 👼🏼

2022-01-31 10:14 UTC, markernst97 approved these changes

2022-02-01 08:43 UTC, RichardPerdaan approved these changes

2022-02-01 15:36 UTC, merged