feat: check and handle shipment options with pickup
myparcelnl/woocommerce pull request #787
Opened 2022-02-07 14:11 UTC by joerivanveen

2022-02-09 09:47 UTC, EdieLemoine requested changes

2022-02-09 09:47 UTC, EdieLemoine commented on includes/admin/OrderSettings.php
> +    /**
entertje

2022-02-09 09:47 UTC, EdieLemoine commented on includes/admin/OrderSettings.php
> +        $deliveryOptions = $this->getDeliveryOptions();
uitlijnen

2022-02-09 09:47 UTC, EdieLemoine commented on includes/admin/OrderSettings.php
> +            '', // already taken into account by 'determineLargeFormat' callback
Waarom niet `null`?

2022-02-09 09:47 UTC, EdieLemoine commented on includes/admin/OrderSettings.php
> +        $this->sameDayDelivery = $this->determineShipmentOption(
Ik vind dit brok wel eng, sommige dingen krijgen ineens true in die parameter en het is een grote foutgevoelige sliert voor mijn gevoel. In zo'n geval zie ik liever een cool loopje waarin je dit doet:

```php
$this->{$property} = $this->determineShipmentOption(
	  [$this->shipmentOptions, $item['shipment_options_method']],
	  $item['setting'],
	  $item['consignment_option'],
	  $item['wat_dit_doet'] ?? false
);
```

Dan hoef je alleen nog goed op te letten dat je array met die spulletjes erin wel klopt en hoef je niet 6x hetzelfde blok code te lezen om er bijvoorbeeld achter te komen of iets wel of niet `wat_dit_doet` gebruikt

2022-02-09 09:47 UTC, EdieLemoine commented on includes/admin/OrderSettings.php
>              } elseif ($productAgeCheck === WCMYPA_Admin::PRODUCT_OPTIONS_ENABLED) {
Omdat je hier toch al een beetje bent... yoda?

2022-02-09 09:47 UTC, EdieLemoine commented on includes/admin/OrderSettings.php
> +    private function showNotWithPickupWarning(string $translatedOptionDesignation): void
Deze hele functie is niet echt human, gaat alles goed? 😂 Zou je een wat meer human understandable v2 kunnen indienen van de functienaam en parameter?

2022-02-09 09:47 UTC, EdieLemoine commented on includes/admin/OrderSettings.php
> +        if (! ($calculatedOptionValueTakesPrecedence && null !== $returnValue) && ! $returnValue) {
Geen grote blij... Kan dit misschien iets leesbaarder?

2022-02-09 09:47 UTC, EdieLemoine commented on includes/admin/OrderSettings.php
> +     * @param bool $calculatedOptionValueTakesPrecedence will return callable() when not null otherwise carrier default
uitlijnen

2022-02-09 09:47 UTC, EdieLemoine commented on includes/admin/OrderSettings.php
> +    private function determineLargeFormat(): bool
deze wordt niet gebruikt volgens de static analysis tool

2022-02-10 13:00 UTC, joerivanveen commented on includes/admin/OrderSettings.php
>              } elseif ($productAgeCheck === WCMYPA_Admin::PRODUCT_OPTIONS_ENABLED) {
Scherp

2022-02-17 14:48 UTC, EdieLemoine approved these changes

2022-02-18 10:26 UTC, merged