feat: add settings for sameday delivery
myparcelnl/woocommerce pull request #797
Opened 2022-02-14 09:18 UTC by markernst97

2022-02-14 10:40 UTC, joerivanveen requested changes

2022-02-14 10:40 UTC, joerivanveen commented on includes/frontend/class-wcmp-checkout.php
> +        $carrierSettings['instabox']['allowSameDayDelivery'] = $this->shouldShowSameDayDelivery();
Dit is nu instabox-specifiek, maar ik zou het hier graag zo zien dat deze functionaliteit ook werkt als je deze instelling (samedaydelivery met de cutoff tijd en de fee) aan een andere carrier toevoegt, als het enigszins mogelijk is. Dus ook in de shouldShowSameDayDelivery method zou ik op een abstracter niveau kijken of dit getoond moet worden niet hardcoded alleen wanneer instabox actief is.

2022-02-14 10:40 UTC, joerivanveen commented on includes/frontend/class-wcmp-checkout.php
> +        $tomorrowIsDropOffDay = in_array(self::DAYS_TO_NUMBER_MAP[date('l')], $dropOffDays, true);
Je kunt uit de date toch ook een 'dag van de week' int krijgen? dan maak je days_to_number_map overbodig en ik ben ook bang dat als je je server op Chinees hebt ingesteld deze mogelijk geen Monday (bv) teruggeeft waardoor je map niet meer werkt? Dat laatste weet ik niet zeker hoor, maar sowieso minder cognitive load als je dagnummers opvraagt direct?

2022-02-14 10:40 UTC, joerivanveen commented on includes/frontend/class-wcmp-checkout.php
> +        $settingCollection    = WCMYPA()->setting_collection->where('carrier', CarrierInstabox::NAME);
Wanneer je hier loopt door de carriers kun je per carrier (zoals je het later ook 'set' op basis van de return van deze method) de sameday setting teruggeven. dus een array met per carrier de sameday setting, dan mergen.

2022-02-14 10:40 UTC, joerivanveen commented on includes/frontend/class-wcmp-checkout.php
> +        $settingCollection    = WCMYPA()->setting_collection->where('carrier', CarrierInstabox::NAME);
Dan krijg je dus ook dat je isInSameDayTimeSlot carrierspecifiek wordt.

2022-02-14 10:40 UTC, joerivanveen commented on includes/frontend/class-wcmp-checkout.php
> +        return ($beforeSameDayCutOffTime && $afterRegularCutOffTime) || ($sameDayCutOffBeforeNormalCutOff && $beforeSameDayCutOffTime);
Ik geloof dat dit werkt en dat je hier goed over nagedacht hebt, maar ik vind het heel moeilijk te lezen hoe je nu eigenlijk het tijdvak bepaalt. Als het ook maar enigszins duidelijker kan graag :-)

2022-02-16 10:00 UTC, RichardPerdaan approved these changes

2022-02-16 15:17 UTC, EdieLemoine requested changes

2022-02-16 15:17 UTC, EdieLemoine commented on includes/frontend/class-wcmp-checkout.php
> +        $noDropOffDelay       = "0" === $settingCollection->getByName(WCMYPA_Settings::SETTING_CARRIER_DROP_OFF_DELAY);
double quotes

2022-02-16 15:17 UTC, EdieLemoine commented on includes/frontend/class-wcmp-checkout.php
> +        return $carrierIsActive && $sameDayFromSettings && $tomorrowIsDropOffDay && $noDropOffDelay && $isInSameDayTimeSlot;
Misschien wordt het beter als je bijvoorbeeld `$tomorrowIsDropOffDay && $noDropOffDelay && $isInSameDayTimeSlot` naar een losse functie trekt. Dan zou ik ook eigenlijk snel willen dat dat niet meer in deze class staat, maar in iets als een `SameDayDeliveryService` oid

2022-02-17 11:35 UTC, joerivanveen requested changes

2022-02-17 11:35 UTC, joerivanveen commented on includes/admin/settings/SameDayDeliveryService.php
> +        if (! $carrierIsActive && ! $sameDayFromSettings) {
Ik weet bijna zeker dat dit || moet zijn ipv &&, graag even dubbelchecken? Waarom zou je anders nog de same day setting willen controleren, als je carrier niet active is...

2022-02-17 11:41 UTC, joerivanveen submitted a review, later dismissed

2022-02-17 12:32 UTC, RichardPerdaan approved these changes

2022-02-17 12:49 UTC, EdieLemoine requested changes

2022-02-17 12:49 UTC, EdieLemoine commented on includes/admin/settings/SameDayDeliveryService.php
> +        $sameDayFromSettings  = (bool) $settingCollection->getByName(WCMYPA_Settings::SETTING_CARRIER_DEFAULT_EXPORT_SAME_DAY_DELIVERY);
extra spaties

2022-02-17 12:49 UTC, EdieLemoine commented on includes/admin/settings/SameDayDeliveryService.php
> +        $now                             = $date->getTimestamp() + $date->getOffset();
extra spaties

2022-02-17 12:49 UTC, EdieLemoine commented on includes/admin/settings/SameDayDeliveryService.php
> +        $date                            = (new DateTime())->setTimezone(new DateTimeZone('Europe/Amsterdam'));
Deze is niet nodig boven onderstaande if statement

2022-02-17 12:49 UTC, EdieLemoine commented on includes/admin/settings/SameDayDeliveryService.php
> +        return $isInSameDayTimeSlot && $hasNoDropOffDelay && $dropOffAvailableTomorrow;
Die functies mag je hier inline schrijven, het voegt nu niets toe om ze als losse variabelen op te schrijven. Het zorgt er nu alleen maar voor dat alle drie de functies altijd aangeroepen worden.

2022-02-17 12:49 UTC, EdieLemoine commented on includes/admin/settings/SameDayDeliveryService.php
> +    private function hasNoDropOffDelay(): bool
Namen met ontkenningen erin vind ik een beetje eng, ik zie persoonlijk liever `! $this->hasDropOffDelay()`

2022-02-17 14:38 UTC, EdieLemoine submitted a review, later dismissed

2022-02-17 14:38 UTC, RichardPerdaan submitted a review, later dismissed

2022-02-24 15:14 UTC, EdieLemoine approved these changes

2022-02-24 15:18 UTC, joerivanveen submitted a review, later dismissed

2022-03-08 15:09 UTC, joerivanveen approved these changes

2022-03-08 15:13 UTC, EdieLemoine requested changes

2022-03-08 15:13 UTC, EdieLemoine commented on includes/admin/settings/SameDayDeliveryService.php
> +                $cutOffTimeFromSettings
rare indenting

2022-03-08 15:13 UTC, EdieLemoine commented on includes/admin/settings/SameDayDeliveryService.php
> +        return in_array((string) (date('N') + 1), $dropOffDays, true);
Misschien is `new DateTime('tomorrow')->format('N');` wat makkelijker te lezen. Je kunt ook nog een constante maken van N als je dat "leuk" vindt, zodat het bij het lezen direct duidelijk is dat je een weekdag ophaalt ofzo. 

Het wordt wat langer maar bij wat er nu staat moest ik helemaal opzoeken wat het precies doet, php heeft nogal wat obscure date dingen :)

2022-03-08 15:13 UTC, EdieLemoine commented on includes/admin/settings/SameDayDeliveryService.php
> +            $this->settingsCollection->getByName(WCMYPA_Settings::SETTING_CARRIER_DROP_OFF_DELAY),
waarom? is falsy niet goed genoeg?

2022-03-08 15:15 UTC, EdieLemoine commented on includes/admin/settings/SameDayDeliveryService.php
> +        $cutOffTime = $this->settingsCollection->getByName(WCMYPA_Settings::SETTING_CARRIER_CUTOFF_TIME);
uitlijnen!!!

2022-03-08 15:15 UTC, EdieLemoine commented on includes/admin/settings/SameDayDeliveryService.php
> +     * @var
😨

2022-03-10 08:52 UTC, joerivanveen approved these changes

2022-03-10 13:58 UTC, EdieLemoine requested changes

2022-03-10 13:58 UTC, EdieLemoine commented on includes/admin/settings/SameDayDeliveryService.php
> +        $tomorrow = new DateTime('tomorrow');
uitlijnen...

2022-03-10 14:15 UTC, EdieLemoine submitted a review, later dismissed

2022-03-10 14:20 UTC, joerivanveen approved these changes

2022-03-11 15:34 UTC, joerivanveen approved these changes

2022-03-14 10:03 UTC, EdieLemoine requested changes

2022-03-18 08:48 UTC, closed without merging