fix: instabox track trace not showing in notes
myparcelnl/woocommerce pull request #798
Opened 2022-02-15 13:32 UTC by markernst97

2022-02-15 13:42 UTC, EdieLemoine requested changes
Misschien `instabox` als scope?

2022-02-15 13:42 UTC, EdieLemoine commented on includes/admin/class-wcmp-api.php
> +
deze newlines mogen weg

2022-02-15 13:42 UTC, EdieLemoine commented on includes/admin/class-wcmp-api.php
> +            $trackTraceCode   = $shipmentData['track_trace'] ?? null;
extra spaties

2022-02-15 15:12 UTC, joerivanveen approved these changes

2022-02-16 15:22 UTC, EdieLemoine requested changes

2022-02-16 15:22 UTC, EdieLemoine commented on includes/admin/class-wcmp-api.php
> +            $trackTraceArray = [];
Kan dit nog(/weer) in een losse functie?

2022-02-17 11:41 UTC, joerivanveen requested changes

2022-02-17 11:41 UTC, joerivanveen commented on includes/admin/class-wcmp-api.php
> +            $trackTraceCode = $shipmentData['track_trace'] ?? null;
`$shipmentData` bestaat niet (meer) hier? Dus datgene wat je hier wilde bereiken gaat denk ik niet gebeuren.

2022-02-22 08:31 UTC, joerivanveen approved these changes

2022-02-24 15:07 UTC, EdieLemoine approved these changes

2022-02-24 15:30 UTC, merged