fix(hotfix): keep showing ordergrid on faulty address
myparcelnl/woocommerce pull request #799
Opened 2022-02-15 14:10 UTC by joerivanveen

2022-02-15 15:10 UTC, EdieLemoine requested changes

2022-02-15 15:10 UTC, EdieLemoine commented on includes/adapter/RecipientFromWCOrder.php
> +        $isUsingSplitAddressFields  = $street || $number || $numberSuffix;
```suggestion
        $isUsingSplitAddressFields = $street || $number || $numberSuffix;
```

2022-02-15 15:10 UTC, EdieLemoine commented on includes/admin/class-wcmypa-admin.php
> +        } catch (\Exception $exception) {
Exception mag je importeren

2022-02-15 15:16 UTC, markernst97 approved these changes

2022-02-16 08:17 UTC, EdieLemoine approved these changes

2022-02-16 10:10 UTC, merged