refactor: carrier specific dropoff point link
myparcelnl/woocommerce pull request #800
Opened 2022-02-16 09:04 UTC by markernst97

2022-02-16 09:58 UTC, RichardPerdaan approved these changes

2022-02-16 15:03 UTC, RichardPerdaan submitted a review, later dismissed

2022-02-16 15:07 UTC, EdieLemoine requested changes

2022-02-16 15:07 UTC, EdieLemoine commented on includes/admin/settings/CarrierSettings.php
> +                Status::LINK_RETAIL_OVERVIEW . "?carrier={$carrier->getId()}"
Kun je dit in een functie gooien? Iets als `getRetailOverviewLink($carrier)`

2022-02-17 11:37 UTC, joerivanveen approved these changes

2022-02-17 12:31 UTC, RichardPerdaan approved these changes

2022-02-17 13:39 UTC, merged