fix: multiple return labels for label in the box
myparcelnl/woocommerce pull request #808
Opened 2022-03-10 16:23 UTC by RichardPerdaan

2022-03-10 16:55 UTC, joerivanveen approved these changes

2022-03-14 15:46 UTC, markernst97 approved these changes

2022-03-14 16:10 UTC, EdieLemoine requested changes

2022-03-14 16:10 UTC, EdieLemoine commented on includes/admin/class-wcmp-export.php
> +        $this->addreturnInTheBox($collection);
casing klopt niet

2022-03-17 08:04 UTC, RichardPerdaan commented on includes/admin/class-wcmp-export.php
> +        $this->addreturnInTheBox($collection);
Raar de method stond goed en phpstorm geeft gewoon aan dat het goed was

2022-03-17 08:08 UTC, merged