feat: add settings for same day delivery
myparcelnl/woocommerce pull request #810
Opened 2022-03-14 11:39 UTC by markernst97

2022-03-14 12:33 UTC, joerivanveen submitted a review, later dismissed

2022-03-14 13:33 UTC, EdieLemoine approved these changes

2022-03-18 08:50 UTC, EdieLemoine requested changes

2022-03-18 08:50 UTC, EdieLemoine commented on includes/admin/settings/class-wcmypa-settings.php
> +    public const SETTING_CARRIER_DEFAULT_EXPORT_LARGE_FORMAT_FROM_WEIGHT      = 'export_large_format_from_weight';
uitlijning klopt niet

2022-03-18 08:50 UTC, EdieLemoine commented on includes/frontend/class-wcmp-cart-fees.php
> +            [$country, $state, $postcode, $city] = $location;
country is unused, volgens mij kan je hem zo schrijven:
```suggestion
            [, $state, $postcode, $city] = $location;
```

2022-03-18 08:50 UTC, EdieLemoine commented on includes/frontend/class-wcmp-cart-fees.php
> +            $deliveryType = 'same_day';
misschien toch even een constante hiervan maken, en dan bij die constante nog een keer toelichten dat het eigenlijk een shipment option is maar wij doen alsof het een delivery type is...

2022-03-18 09:08 UTC, joerivanveen approved these changes

2022-03-18 10:31 UTC, EdieLemoine approved these changes

2022-03-18 10:31 UTC, merged