feat: show message when order management is enabled
myparcelnl/woocommerce pull request #815
Opened 2022-03-29 14:32 UTC by markernst97

2022-03-29 15:32 UTC, joerivanveen submitted a review, later dismissed

2022-04-01 08:50 UTC, EdieLemoine requested changes

2022-04-01 08:50 UTC, EdieLemoine commented on includes/admin/class-wcmp-export-consignments.php
> +        $dateOfToday      = date("Y-m-d");
quotes

2022-04-01 08:50 UTC, EdieLemoine commented on includes/admin/settings/class-wcmp-settings-data.php
> +        if ('pps' === WCMYPA()->setting_collection->getByName(WCMYPA_Settings::SETTING_EXPORT_MODE)) {
is hier geen constante voor?

2022-04-01 08:50 UTC, EdieLemoine commented on includes/admin/settings/class-wcmp-settings-data.php
> +                'help_text' => __(
dubbele vertaling?

2022-04-01 08:50 UTC, EdieLemoine commented on includes/admin/settings/class-wcmp-settings-data.php
>                  'default' => self::EXPORT_MODE_SHIPMENTS,
uitlijnen

2022-04-01 08:50 UTC, EdieLemoine commented on includes/admin/settings/class-wcmp-settings-data.php
> +    private function getExportModeDescription(): string
phpdoc en quotes

2022-04-04 14:15 UTC, joerivanveen requested changes

2022-04-04 14:15 UTC, joerivanveen commented on includes/admin/settings/class-wcmp-settings-data.php
> +                //                'class'   => [$exportModeClassName],
Waarom is deze comment er?

2022-04-04 14:28 UTC, EdieLemoine requested changes

2022-04-04 14:28 UTC, EdieLemoine commented on includes/admin/settings/class-wcmp-settings-data.php
> +                //                'class'   => [$exportModeClassName],
+1

2022-04-04 15:07 UTC, joerivanveen submitted a review, later dismissed

2022-04-04 15:08 UTC, RichardPerdaan submitted a review, later dismissed

2022-04-04 15:19 UTC, RichardPerdaan submitted a review, later dismissed

2022-04-04 15:30 UTC, joerivanveen approved these changes

2022-04-04 15:34 UTC, RichardPerdaan approved these changes

2022-04-04 15:48 UTC, merged