feat: order status change after label print in backoffice
myparcelnl/woocommerce pull request #831
Opened 2022-05-05 11:14 UTC by markernst97

2022-05-10 08:00 UTC, EdieLemoine requested changes

2022-05-12 07:55 UTC, joerivanveen requested changes
Naast 2 opmerkingen nog een algemene: ik vind het niet logisch dat deze order / shipment logica in de accountsettingsservice staat, want het heeft niet zoveel met accountsettings te maken. Kan er een aparte class voor bestaan?

2022-05-12 07:55 UTC, joerivanveen commented on includes/Settings/Api/AccountSettingsService.php
> +        $orderId     = $jsonBody['data']['hooks'][0]['order'] ?? null;
Is het mogelijk om in de variabelenaam duidelijk te maken dat dit de uuid is die de api eraan heeft gegeven, en dus niet 1 van de orderIds is binnen wooc zelf? en het klopt dus echt dat deze uuid in het veld 'order' zit? ['data']['hooks'][0]['order'], niet ['order']['identifier'] ofzo? Het lijkt onlogisch.

2022-05-17 14:24 UTC, joerivanveen submitted a review, later dismissed

2022-05-20 15:01 UTC, EdieLemoine requested changes

2022-05-20 15:01 UTC, EdieLemoine commented on includes/Webhook/Hooks/OrderStatusWebhook.php
> +        $changeOrderStatusAfter = WCMP_Export_Consignments::getSetting(WCMYPA_Settings::SETTING_CHANGE_ORDER_STATUS_AFTER);
dit ook in een eigen functie

2022-05-20 15:01 UTC, EdieLemoine commented on includes/Webhook/Hooks/OrderStatusWebhook.php
> +        $changeOrderStatusAfter = WCMP_Export_Consignments::getSetting(WCMYPA_Settings::SETTING_CHANGE_ORDER_STATUS_AFTER);
Misschien kun je ook even kritisch kijken naar de overeenkomsten tussen de classes in `Webhook/Hooks`, die kunnen waarschijnlijk gewoon allebei dezelfde parent class gebruiken waardoor er wat code weg kan

2022-05-24 07:45 UTC, joerivanveen submitted a review, later dismissed

2022-05-24 14:11 UTC, joerivanveen submitted a review, later dismissed

2022-05-25 06:49 UTC, RichardPerdaan submitted a review, later dismissed

2022-05-27 14:31 UTC, RichardPerdaan approved these changes

2022-05-27 14:33 UTC, joerivanveen approved these changes

2022-05-27 14:34 UTC, merged