fix:fix auto export function
myparcelnl/woocommerce pull request #835
Opened 2022-06-02 12:53 UTC by wthijmen

2022-06-02 12:55 UTC, EdieLemoine commented
pr titel is niet correct, er mist een spatie

https://www.conventionalcommits.org/en/v1.0.0/#specification

2022-06-02 12:55 UTC, EdieLemoine requested changes

2022-06-02 12:55 UTC, EdieLemoine commented on includes/frontend/class-wcmp-frontend.php
> +        if(! isset(WC()->session)) {
formatting

2022-06-02 12:55 UTC, EdieLemoine commented on includes/frontend/class-wcmp-frontend.php
> +            return '';
Liever geen lege strings gebruiken, dan is het beter om null te returnen en expliciet in bovenstaande functie te controleren of er wat uit is gekomen.

2022-06-02 15:07 UTC, joerivanveen approved these changes

2022-06-07 14:08 UTC, EdieLemoine approved these changes

2022-06-08 07:02 UTC, merged