fix(om): error when delivery options absent
myparcelnl/woocommerce pull request #845
Opened 2022-06-22 08:42 UTC by Mark-Ernst

Resolves #843

2022-06-22 10:44 UTC, EdieLemoine requested changes

2022-06-22 10:44 UTC, EdieLemoine commented on includes/admin/class-wcmp-export.php
> +        } catch(Exception $e) {
formatting klopt niet

2022-06-22 10:44 UTC, EdieLemoine commented on includes/admin/class-wcmp-export.php
> +            $savedOrderCollection = $this->orderCollection->save();
Oei, dit vind ik geen fijne structuur, `save` impliceert iets wat gewoon `void` of `self` teruggeeft en dan evt het originele item (`orderCollection`) wijzigt... Maar dit heeft verder niks met je pr te maken hoor, ik wilde het alleen even zeggen voor de "toekomst" 😛

2022-06-22 10:44 UTC, EdieLemoine commented on includes/adapter/delivery-options-from-order-adapter.php
> +        $adapterPackageType    = $originAdapter ? $originAdapter->getPackageType() : AbstractConsignment::DEFAULT_PACKAGE_TYPE_NAME;
Kan niet wachten tot ~2030~ 2023 🤩, wanneer heel php 7 EOL is en we dit mogen doen:

```php
return $originAdapter?->getPackageType();
``` 
_(Waar het niet dat WordPress in 2030 waarschijnlijk nog steeds op php 7 zit...)_

2022-06-22 10:44 UTC, EdieLemoine commented on includes/class-wcmp-data.php
> +    public const DEFAULT_CARRIER_NAME  = CarrierPostNL::NAME;
`(self::DEFAULT_CARRIER_CLASS)::ID`
`(self::DEFAULT_CARRIER_CLASS)::NAME`

of daar gewoon zo schrijven. Ik vind het ook niet heel mooi zo, maar het punt van alleen de `CLASS` hebben is dat je daarmee ook bij die consts kan komen

2022-06-23 07:13 UTC, joerivanveen submitted a review, later dismissed

2022-06-24 07:30 UTC, wthijmen approved these changes

2022-06-24 09:03 UTC, merged