fix: validate api key to prevent unnecessary calls
myparcelnl/woocommerce pull request #846
Opened 2022-06-22 09:45 UTC by Mark-Ernst

2022-06-22 10:32 UTC, EdieLemoine requested changes

2022-06-22 10:32 UTC, EdieLemoine commented on includes/admin/settings/Status.php
> +        update_option('myparcel_valid_api_key', $allWebhooksPresent);
al onze opties heten `woocommerce_myparcel_x`, dus deze moet ook wel een soortgelijke naam hebben voor consistentie

2022-06-22 10:32 UTC, EdieLemoine commented on includes/admin/settings/Status.php
> +        (new AccountSettingsWebhook())->register();
Ik vind dit wel een beetje een rare plek om dit te doen, de bedoeling is dat dit gewoon kijkt naar de status van zaken. 

Kan dit niet ergens in het opstartproces van de plugin? Desnoods maak je ergens een globale functie om te kijken of alle webhooks geregistreerd zijn, maar je moet niet webhooks aanmaken en settings aanpassen in code die alleen een stukje interface zou moeten renderen. Zo is het onlogisch en zorgt het er ook voor dat het heel moeilijk wordt om terug te vinden waar dit precies gedaan wordt.

2022-06-23 10:09 UTC, joerivanveen requested changes
Ik heb het gevoel dat nog niet de beste oplossing voor het probleem is gevonden.

2022-06-23 10:09 UTC, joerivanveen commented on includes/admin/settings/Status.php
> +        update_option('myparcel_valid_api_key', $allWebhooksPresent);
Ik zie nu dat dit een boolean is, en dat er niet een valid api key in staat, daarom zou ik het bv woocommerce_myparcel_api_key_is_valid in zetten. Maar dan nog vind ik het de lading niet helemaal dekken, dat kan wel komen doordat ik niet alles doorzie (waarom betekent het dat de api key goed is als alle webhooks present zijn? er wordt toch geen communicatie gecheckt?).

2022-06-23 10:09 UTC, joerivanveen commented on woocommerce-myparcel.php
> +            if ($validApiKey !== $currentApiKey) {
Ik vind $validApiKey een beetje misleidend als het klopt wat ik in de code lees, want dan wordt niet gecheckt of de api key valid is. En wat is er met de apikeysettingslistener

2022-06-23 10:09 UTC, joerivanveen commented on woocommerce-myparcel.php
> +            if ($validApiKey !== $currentApiKey) {
Het lijkt erop alsof je hier een boolean gaat checken tegen een string, dit zal toch altijd false zijn?

2022-06-28 14:43 UTC, joerivanveen requested changes
Het belangrijkste dat ik zie (maar je gaf al aan dat je nog iets gaat aanpassen) is dat de accountsettings eigenlijk ook geladen moeten worden door de apikeysettingslistener nu, en je moet niet vertrouwen op dat je ze weggooit en dat ze dan bij het volgende request geladen worden (dat moet dus weg, waar dat nu zit, weet ik niet uit mijn hoofd), omdat dat hetzelfde 'probleem'. is als we nu hebben, alleen minder erg want maar 1 keer per request.

2022-06-28 14:43 UTC, joerivanveen commented on includes/Webhook/Service/WebhookSubscriptionService.php
> +                $allWebhooksPresent = false;
Ik zou hier doen `return false;` (want je hoeft niet verder te loopen) en aan het eind. `return true;` dan kan je ook de $allWebhooksPresent var weglaten.

2022-06-28 14:43 UTC, joerivanveen commented on includes/Webhook/Service/WebhookSubscriptionService.php
> +            $webhookCallback = $webhookSubscriptionService->createCallbackUrl($service, 'v1');
De version is niet superbelangrijk (nu), maar als we veranderen hoe het werkt wel, ik zou hem daarom wat meer exposed maken (bv als constante) niet als een string 'diep'. weggestopt.

2022-06-30 16:28 UTC, wthijmen requested changes

2022-07-01 09:37 UTC, wthijmen submitted a review, later dismissed

2022-07-01 09:56 UTC, wthijmen approved these changes

2022-07-01 13:41 UTC, joerivanveen requested changes

2022-07-01 13:41 UTC, joerivanveen commented on woocommerce-myparcel.php
> +            (new OrderStatusWebhook())->register();
Dit ziet er goed uit, dat je deze rest-url altijd aanmaakt, alleen dan verwacht ik wel de check die gedaan werd, of er wel iets geautomatiseerd moet worden, in de orderstatuswebhook, en daar zie ik geen wijzigingen in deze pr, ik heb nu dus het idee dat de status altijd gezet wordt, ongeacht de instellingen in de plugin. Graag uitleg waarom dat niet zo is, of het fixen :-)

2022-07-04 14:38 UTC, joerivanveen approved these changes

2022-07-06 06:48 UTC, merged