fix: allow numbers as suffix using myparcel address fields
myparcelnl/woocommerce pull request #850
Opened 2022-06-27 18:07 UTC by joerivanveen

2022-06-28 14:39 UTC, Mark-Ernst submitted a review, later dismissed

2022-06-30 07:39 UTC, joerivanveen commented on includes/adapter/RecipientFromWCOrder.php
> +                $streetParts['number_suffix'] ??  null,
```suggestion
                $streetParts['number_suffix'] ?? null,
```

2022-06-30 08:34 UTC, EdieLemoine requested changes

2022-06-30 08:34 UTC, EdieLemoine commented on includes/adapter/RecipientFromWCOrder.php
> +            $streetParts['number_suffix'] = sprintf(' -%d', abs($streetParts['number_suffix']));
...ik was aan het schrijven waarom ik dit raar en eng vond, maar ik snap nu dat dit een "hack" is om het streepje er vanaf te halen... clever, maar niet vanzelfsprekend, graag een comment erboven plaatsen. Als je de code leesbaar wilt maken moet je het helemaal uitschrijven dus in dit geval is een comment ook goed

2022-06-30 08:34 UTC, EdieLemoine commented on includes/class-wcmp-postcode-fields.php
> +        $shipToDifferentAddress = isset($_POST['ship_to_different_address']);
kun je alle $_POST stuff gewoon een keer sanitizen? dan zijn we ook van die meldingen af

2022-06-30 09:29 UTC, EdieLemoine approved these changes

2022-06-30 09:52 UTC, wthijmen approved these changes

2022-07-01 10:41 UTC, merged