refactor: get local pickup method id instead of human string
myparcelnl/woocommerce pull request #860
Opened 2022-07-26 15:32 UTC by Mark-Ernst

2022-07-26 16:07 UTC, joerivanveen submitted a review, later dismissed

2022-07-27 07:29 UTC, EdieLemoine requested changes

2022-07-27 07:29 UTC, EdieLemoine commented on includes/admin/class-wcmypa-admin.php
> +        $shippingMethods      = $order->get_shipping_methods();
uitlijnen

2022-07-27 07:29 UTC, EdieLemoine commented on includes/admin/class-wcmypa-admin.php
> +        return WCMP_Shipping_Methods::LOCAL_PICKUP === $shippingMethodId;
We moeten stoppen met WCMYPA vol zetten met onnodige methods (en überhaupt de hele plugin met static methods). 

Deze functie returnt iets over een WC_Order, ik zou hem dan ook op een plek zetten waar het normaal is om info over een order op te vragen, of in WCMP_Shipping_Methods oid

2022-07-27 11:55 UTC, wthijmen approved these changes

2022-07-28 11:43 UTC, joerivanveen approved these changes

2022-07-28 11:48 UTC, wthijmen approved these changes

2022-07-29 11:01 UTC, EdieLemoine requested changes

2022-07-29 11:01 UTC, EdieLemoine commented on includes/admin/class-wcmp-export.php
> +            $orderSettings = new OrderSettings($order);
uitlijnen

2022-08-01 07:35 UTC, joerivanveen submitted a review, later dismissed

2022-08-01 07:36 UTC, EdieLemoine submitted a review, later dismissed

2022-08-01 07:45 UTC, wthijmen approved these changes

2022-08-09 13:17 UTC, Mark-Ernst commented
/rebase

2022-08-15 07:51 UTC, wthijmen approved these changes

2022-08-15 07:52 UTC, EdieLemoine approved these changes

2022-08-15 08:00 UTC, merged