feat: add modal option for myparcel orders only
myparcelnl/woocommerce pull request #869
Opened 2022-08-25 15:23 UTC by Mark-Ernst

Resolves #867

2022-08-26 07:10 UTC, wthijmen requested changes

2022-08-26 07:10 UTC, wthijmen commented on includes/admin/views/MyParcelWidget.php
> +            if (in_array($shippingClass . ':' . $highestShippingClass, $shippingMethods, true)) {
Geen concatenation

2022-08-26 07:10 UTC, wthijmen commented on includes/admin/views/MyParcelWidget.php
> +        array_walk_recursive($array, static function ($a) use (&$return) { $return[] = $a; });
Geen byref en codacy en enter return

2022-08-26 07:10 UTC, wthijmen commented on includes/admin/views/MyParcelWidget.php
> +                esc_attr(__('show_myparcel_orders_only', 'woocommerce-myparcel')),
show_myparcel_orders_only wordt niet meer gebruikt

2022-08-26 08:56 UTC, wthijmen submitted a review, later dismissed

2022-08-30 14:42 UTC, EdieLemoine submitted a review, later dismissed

2022-09-06 09:14 UTC, joerivanveen commented on includes/admin/class-wcmp-export.php
> +        if ($chosenMethod === WCMP_Shipping_Methods::LEGACY_FLAT_RATE || version_compare(WOOCOMMERCE_VERSION, '2.6', '<')) {
Wat mij betreft niet blokkerend maar die wooc version check kan er wel uit, we ondersteunen toch niet meer < 5

2022-09-06 09:25 UTC, joerivanveen requested changes

2022-09-06 09:25 UTC, joerivanveen commented on includes/admin/views/MyParcelWidget.php
> +    private function findHighestShippingClass(WC_Order $order): ?string
Wat mij betreft mag deze ook weg, want niet meer gebruikt.

2022-09-06 13:59 UTC, joerivanveen approved these changes

2022-09-14 07:11 UTC, wthijmen approved these changes

2022-09-15 14:06 UTC, EdieLemoine approved these changes
vage pr titel, kun je er iets duidelijkers van maken?

2022-09-18 06:28 UTC, Martje65 commented
Zoals het nu is zullen de geannuleerde bestellingen nog steeds in de MyParcel widget zichtbaar zijn.

Op de screenshot hieronder is de status van bestelling 3112 geannuleerd.

![MyParcel widget new](https://user-images.githubusercontent.com/112067446/190888744-d5f5e7bb-e172-4988-b4be-e136c3f3355b.jpg)

2022-09-27 08:40 UTC, wthijmen submitted a review, later dismissed

2022-09-27 14:24 UTC, EdieLemoine requested changes

2022-09-27 14:24 UTC, EdieLemoine commented on includes/admin/views/MyParcelWidget.php
> +            if (self::CLASS_WC_ORDER !== get_parent_class($order)) {
`is_a($order, \WC_Order)`

2022-09-27 14:24 UTC, EdieLemoine commented on includes/admin/views/MyParcelWidget.php
> +        return "<tr onclick=\"window.location='/wp-admin/post.php?post={$orderId}&action=edit';\" style=\"cursor: pointer !important;\">
👍🏼

2022-09-29 08:13 UTC, wthijmen submitted a review, later dismissed

2022-09-30 07:28 UTC, wthijmen approved these changes

2022-09-30 09:18 UTC, joerivanveen approved these changes

2022-11-11 09:05 UTC, wthijmen approved these changes

2022-11-11 09:05 UTC, joerivanveen approved these changes

2022-11-11 09:16 UTC, wthijmen approved these changes

2022-11-11 09:16 UTC, joerivanveen approved these changes

2022-11-11 09:18 UTC, EdieLemoine approved these changes

2022-11-11 09:43 UTC, merged