fix: prevent external translations
myparcelnl/woocommerce pull request #873
Opened 2022-08-30 08:42 UTC by joerivanveen

Resolves #872

2022-08-30 13:35 UTC, EdieLemoine requested changes

2022-08-30 13:35 UTC, EdieLemoine commented on woocommerce-myparcel.php
> +            load_textdomain(self::DOMAIN, __DIR__ . '/languages/' . self::DOMAIN . '-' . $locale . '.mo');
verander meteen ff die concat dan

2022-08-30 14:21 UTC, EdieLemoine approved these changes

2022-08-31 12:03 UTC, RichardPerdaan approved these changes

2022-09-02 06:49 UTC, merged