feat: show digital stamp weight in order view
myparcelnl/woocommerce pull request #896
Opened 2022-10-18 15:26 UTC by Mark-Ernst

Resolves #478

2022-10-19 07:22 UTC, wthijmen submitted a review, later dismissed

2022-10-24 11:05 UTC, joerivanveen requested changes

2022-10-24 11:05 UTC, joerivanveen commented on includes/admin/class-wcmypa-admin.php
> +        $packageType = (new WCMP_Export())->getAllowedPackageType($order, $orderSettings->getPackageType());
uitlijning =

2022-10-24 11:05 UTC, joerivanveen commented on includes/admin/OrderSettings.php
> +    public function getDigitalStampRange(): array
Ik denk dat je deze empty weight dan lokaal moet toevoegen aan $orderWeight verderop.

2022-10-25 08:23 UTC, joerivanveen submitted a review, later dismissed

2022-10-25 08:31 UTC, wthijmen approved these changes

2022-10-25 13:16 UTC, wthijmen approved these changes

2022-10-27 11:17 UTC, joerivanveen approved these changes

2022-10-27 13:12 UTC, merged