build: prevent missing folders during svn deploy
myparcelnl/woocommerce pull request #902
Opened 2022-11-03 15:18 UTC by joerivanveen

2022-11-04 08:30 UTC, EdieLemoine requested changes

2022-11-04 08:30 UTC, EdieLemoine commented on .github/workflows/release.yml
> +        if: steps.release.outputs.released == true
```suggestion
        if: steps.release.outputs.released == 'true'
```

https://docs.github.com/en/actions/learn-github-actions/expressions#functions

2022-11-08 10:35 UTC, wthijmen approved these changes

2022-11-10 08:33 UTC, EdieLemoine requested changes

2022-11-11 08:13 UTC, wthijmen approved these changes

2022-11-11 08:30 UTC, EdieLemoine approved these changes

2022-11-11 08:42 UTC, merged