feat: add insurance options for eu shipments
myparcelnl/woocommerce pull request #922
Opened 2022-11-29 14:24 UTC by Mark-Ernst

2022-11-30 09:26 UTC, wthijmen submitted a review, later dismissed

2022-12-01 08:55 UTC, joerivanveen requested changes
Ik mis nog het stukje waar hij de EU insurance amount zet op basis van alle parameters bij exporteren, mogelijk begrijp ik iets niet dan graag uitleg waarom het zou werken. Volgens mij werkt dit nu niet zo out of the box.

2022-12-01 08:55 UTC, joerivanveen commented on includes/admin/OrderSettingsRows.php
> +    private const EU_INSURANCE_OPTIONS = [
Hoor je dit niet uit de carrier / consignment te halen... ik zie nu wel een probleempje met de gekozen oplossing, door dit niet op dezelfde manier te laten werken als de NL insurance amounts, kan dit niet meer per carrier verschillen?

2022-12-06 08:12 UTC, wthijmen approved these changes

2022-12-06 15:33 UTC, joerivanveen requested changes

2022-12-06 15:33 UTC, joerivanveen commented on includes/admin/OrderSettings.php
> +        $amountPossibilities = $isEu ? $carrier->getEuInsurancePossibilities() : $carrier->getInsurancePossibilities();
Dan wordt het hier logischer, je kunt nl. $consignment->getInsurancePossibilities(ISO2landcode) doen, volgens de huidige versie van de branch in de sdk waar deze wijzigingen in zitten. Daar is ook het conflict van de protected / public method van getEuInsurancePossibilities() opgelost en je kunt die method dus NIET meer direct aanroepen (is niet meer public).

2022-12-15 08:47 UTC, joerivanveen submitted a review, later dismissed

2023-01-03 08:52 UTC, wthijmen approved these changes

2023-01-03 09:22 UTC, EdieLemoine approved these changes

2023-01-03 09:24 UTC, merged