chore: bump delivery options
myparcelnl/woocommerce pull request #982
Opened 2023-05-24 12:09 UTC by Mark-Ernst

2023-05-24 12:09 UTC, EdieLemoine requested changes

2023-05-24 12:09 UTC, EdieLemoine commented on package.json
> -    "@myparcel/delivery-options": "^5.7.3"
dit hoeft niet

2023-05-24 12:09 UTC, EdieLemoine commented on composer.lock
Deze hoort er niet in te zitten

2023-05-25 07:26 UTC, joerivanveen approved these changes

2023-05-25 07:57 UTC, EdieLemoine approved these changes

2023-05-25 07:57 UTC, EdieLemoine approved these changes

2023-05-25 07:58 UTC, merged